// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 25 prop entries from assets/kenney/mini-dungeon.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "mini-dungeon-banner", asset: "/assets/kenney/mini-dungeon/banner.glb", name: "Mini Dungeon: Banner" },
  { slug: "mini-dungeon-barrel", asset: "/assets/kenney/mini-dungeon/barrel.glb", name: "Mini Dungeon: Barrel" },
  { slug: "mini-dungeon-character-human", asset: "/assets/kenney/mini-dungeon/character-human.glb", name: "Mini Dungeon: Human" },
  { slug: "mini-dungeon-character-orc", asset: "/assets/kenney/mini-dungeon/character-orc.glb", name: "Mini Dungeon: Orc" },
  { slug: "mini-dungeon-chest", asset: "/assets/kenney/mini-dungeon/chest.glb", name: "Mini Dungeon: Chest" },
  { slug: "mini-dungeon-coin", asset: "/assets/kenney/mini-dungeon/coin.glb", name: "Mini Dungeon: Coin" },
  { slug: "mini-dungeon-column", asset: "/assets/kenney/mini-dungeon/column.glb", name: "Mini Dungeon: Column" },
  { slug: "mini-dungeon-dirt", asset: "/assets/kenney/mini-dungeon/dirt.glb", name: "Mini Dungeon: Dirt" },
  { slug: "mini-dungeon-floor-detail", asset: "/assets/kenney/mini-dungeon/floor-detail.glb", name: "Mini Dungeon: Detail" },
  { slug: "mini-dungeon-floor", asset: "/assets/kenney/mini-dungeon/floor.glb", name: "Mini Dungeon: Floor" },
  { slug: "mini-dungeon-gate", asset: "/assets/kenney/mini-dungeon/gate.glb", name: "Mini Dungeon: Gate" },
  { slug: "mini-dungeon-rocks", asset: "/assets/kenney/mini-dungeon/rocks.glb", name: "Mini Dungeon: Rocks" },
  { slug: "mini-dungeon-shield-rectangle", asset: "/assets/kenney/mini-dungeon/shield-rectangle.glb", name: "Mini Dungeon: Rectangle" },
  { slug: "mini-dungeon-shield-round", asset: "/assets/kenney/mini-dungeon/shield-round.glb", name: "Mini Dungeon: Round" },
  { slug: "mini-dungeon-stairs", asset: "/assets/kenney/mini-dungeon/stairs.glb", name: "Mini Dungeon: Stairs" },
  { slug: "mini-dungeon-stones", asset: "/assets/kenney/mini-dungeon/stones.glb", name: "Mini Dungeon: Stones" },
  { slug: "mini-dungeon-trap", asset: "/assets/kenney/mini-dungeon/trap.glb", name: "Mini Dungeon: Trap" },
  { slug: "mini-dungeon-wall-half", asset: "/assets/kenney/mini-dungeon/wall-half.glb", name: "Mini Dungeon: Half" },
  { slug: "mini-dungeon-wall-narrow", asset: "/assets/kenney/mini-dungeon/wall-narrow.glb", name: "Mini Dungeon: Narrow" },
  { slug: "mini-dungeon-wall-opening", asset: "/assets/kenney/mini-dungeon/wall-opening.glb", name: "Mini Dungeon: Opening" },
  { slug: "mini-dungeon-wall", asset: "/assets/kenney/mini-dungeon/wall.glb", name: "Mini Dungeon: Wall" },
  { slug: "mini-dungeon-weapon-spear", asset: "/assets/kenney/mini-dungeon/weapon-spear.glb", name: "Mini Dungeon: Spear" },
  { slug: "mini-dungeon-weapon-sword", asset: "/assets/kenney/mini-dungeon/weapon-sword.glb", name: "Mini Dungeon: Sword" },
  { slug: "mini-dungeon-wood-structure", asset: "/assets/kenney/mini-dungeon/wood-structure.glb", name: "Mini Dungeon: Structure" },
  { slug: "mini-dungeon-wood-support", asset: "/assets/kenney/mini-dungeon/wood-support.glb", name: "Mini Dungeon: Support" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
