// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 44 building entries from assets/quaternius/medieval_village_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-village-bag", asset: "/assets/quaternius/medieval_village_pack/bag.glb", name: "Quat Village: Bag" },
  { slug: "quat-village-bag_open", asset: "/assets/quaternius/medieval_village_pack/bag_open.glb", name: "Quat Village: Bag Open" },
  { slug: "quat-village-bags", asset: "/assets/quaternius/medieval_village_pack/bags.glb", name: "Quat Village: Bags" },
  { slug: "quat-village-barrel", asset: "/assets/quaternius/medieval_village_pack/barrel.glb", name: "Quat Village: Barrel" },
  { slug: "quat-village-bell", asset: "/assets/quaternius/medieval_village_pack/bell.glb", name: "Quat Village: Bell" },
  { slug: "quat-village-bell_tower", asset: "/assets/quaternius/medieval_village_pack/bell_tower.glb", name: "Quat Village: Bell Tower" },
  { slug: "quat-village-bench_1", asset: "/assets/quaternius/medieval_village_pack/bench_1.glb", name: "Quat Village: Bench 1" },
  { slug: "quat-village-bench_2", asset: "/assets/quaternius/medieval_village_pack/bench_2.glb", name: "Quat Village: Bench 2" },
  { slug: "quat-village-blacksmith", asset: "/assets/quaternius/medieval_village_pack/blacksmith.glb", name: "Quat Village: Blacksmith" },
  { slug: "quat-village-bonfire", asset: "/assets/quaternius/medieval_village_pack/bonfire.glb", name: "Quat Village: Bonfire" },
  { slug: "quat-village-bonfire_lit", asset: "/assets/quaternius/medieval_village_pack/bonfire_lit.glb", name: "Quat Village: Bonfire Lit" },
  { slug: "quat-village-cart", asset: "/assets/quaternius/medieval_village_pack/cart.glb", name: "Quat Village: Cart" },
  { slug: "quat-village-cauldron", asset: "/assets/quaternius/medieval_village_pack/cauldron.glb", name: "Quat Village: Cauldron" },
  { slug: "quat-village-crate", asset: "/assets/quaternius/medieval_village_pack/crate.glb", name: "Quat Village: Crate" },
  { slug: "quat-village-door_round", asset: "/assets/quaternius/medieval_village_pack/door_round.glb", name: "Quat Village: Door Round" },
  { slug: "quat-village-door_straight", asset: "/assets/quaternius/medieval_village_pack/door_straight.glb", name: "Quat Village: Door Straight" },
  { slug: "quat-village-fence", asset: "/assets/quaternius/medieval_village_pack/fence.glb", name: "Quat Village: Fence" },
  { slug: "quat-village-gazebo", asset: "/assets/quaternius/medieval_village_pack/gazebo.glb", name: "Quat Village: Gazebo" },
  { slug: "quat-village-hay", asset: "/assets/quaternius/medieval_village_pack/hay.glb", name: "Quat Village: Hay" },
  { slug: "quat-village-house_1", asset: "/assets/quaternius/medieval_village_pack/house_1.glb", name: "Quat Village: House 1" },
  { slug: "quat-village-house_2", asset: "/assets/quaternius/medieval_village_pack/house_2.glb", name: "Quat Village: House 2" },
  { slug: "quat-village-house_3", asset: "/assets/quaternius/medieval_village_pack/house_3.glb", name: "Quat Village: House 3" },
  { slug: "quat-village-house_4", asset: "/assets/quaternius/medieval_village_pack/house_4.glb", name: "Quat Village: House 4" },
  { slug: "quat-village-inn", asset: "/assets/quaternius/medieval_village_pack/inn.glb", name: "Quat Village: Inn" },
  { slug: "quat-village-marketstand_1", asset: "/assets/quaternius/medieval_village_pack/marketstand_1.glb", name: "Quat Village: Marketstand 1" },
  { slug: "quat-village-marketstand_2", asset: "/assets/quaternius/medieval_village_pack/marketstand_2.glb", name: "Quat Village: Marketstand 2" },
  { slug: "quat-village-mill", asset: "/assets/quaternius/medieval_village_pack/mill.glb", name: "Quat Village: Mill" },
  { slug: "quat-village-package_1", asset: "/assets/quaternius/medieval_village_pack/package_1.glb", name: "Quat Village: Package 1" },
  { slug: "quat-village-package_2", asset: "/assets/quaternius/medieval_village_pack/package_2.glb", name: "Quat Village: Package 2" },
  { slug: "quat-village-path_square", asset: "/assets/quaternius/medieval_village_pack/path_square.glb", name: "Quat Village: Path Square" },
  { slug: "quat-village-path_straight", asset: "/assets/quaternius/medieval_village_pack/path_straight.glb", name: "Quat Village: Path Straight" },
  { slug: "quat-village-rock_1", asset: "/assets/quaternius/medieval_village_pack/rock_1.glb", name: "Quat Village: Rock 1" },
  { slug: "quat-village-rock_2", asset: "/assets/quaternius/medieval_village_pack/rock_2.glb", name: "Quat Village: Rock 2" },
  { slug: "quat-village-rock_3", asset: "/assets/quaternius/medieval_village_pack/rock_3.glb", name: "Quat Village: Rock 3" },
  { slug: "quat-village-sawmill", asset: "/assets/quaternius/medieval_village_pack/sawmill.glb", name: "Quat Village: Sawmill" },
  { slug: "quat-village-sawmill_saw", asset: "/assets/quaternius/medieval_village_pack/sawmill_saw.glb", name: "Quat Village: Sawmill Saw" },
  { slug: "quat-village-smoke", asset: "/assets/quaternius/medieval_village_pack/smoke.glb", name: "Quat Village: Smoke" },
  { slug: "quat-village-stable", asset: "/assets/quaternius/medieval_village_pack/stable.glb", name: "Quat Village: Stable" },
  { slug: "quat-village-stairs", asset: "/assets/quaternius/medieval_village_pack/stairs.glb", name: "Quat Village: Stairs" },
  { slug: "quat-village-well", asset: "/assets/quaternius/medieval_village_pack/well.glb", name: "Quat Village: Well" },
  { slug: "quat-village-window_1", asset: "/assets/quaternius/medieval_village_pack/window_1.glb", name: "Quat Village: Window 1" },
  { slug: "quat-village-window_2", asset: "/assets/quaternius/medieval_village_pack/window_2.glb", name: "Quat Village: Window 2" },
  { slug: "quat-village-window_3", asset: "/assets/quaternius/medieval_village_pack/window_3.glb", name: "Quat Village: Window 3" },
  { slug: "quat-village-window_4", asset: "/assets/quaternius/medieval_village_pack/window_4.glb", name: "Quat Village: Window 4" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "building", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
