// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 20 prop entries from assets/kenney/mini-skate.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "mini-skate-bowl-corner-inner", asset: "/assets/kenney/mini-skate/bowl-corner-inner.glb", name: "Mini Skate: Corner-Inner" },
  { slug: "mini-skate-bowl-corner-outer", asset: "/assets/kenney/mini-skate/bowl-corner-outer.glb", name: "Mini Skate: Corner-Outer" },
  { slug: "mini-skate-bowl-side", asset: "/assets/kenney/mini-skate/bowl-side.glb", name: "Mini Skate: Side" },
  { slug: "mini-skate-character-skate-boy", asset: "/assets/kenney/mini-skate/character-skate-boy.glb", name: "Mini Skate: Skate-Boy" },
  { slug: "mini-skate-character-skate-girl", asset: "/assets/kenney/mini-skate/character-skate-girl.glb", name: "Mini Skate: Skate-Girl" },
  { slug: "mini-skate-floor-concrete", asset: "/assets/kenney/mini-skate/floor-concrete.glb", name: "Mini Skate: Concrete" },
  { slug: "mini-skate-floor-wood", asset: "/assets/kenney/mini-skate/floor-wood.glb", name: "Mini Skate: Wood" },
  { slug: "mini-skate-half-pipe", asset: "/assets/kenney/mini-skate/half-pipe.glb", name: "Mini Skate: Pipe" },
  { slug: "mini-skate-obstacle-box", asset: "/assets/kenney/mini-skate/obstacle-box.glb", name: "Mini Skate: Box" },
  { slug: "mini-skate-obstacle-end", asset: "/assets/kenney/mini-skate/obstacle-end.glb", name: "Mini Skate: End" },
  { slug: "mini-skate-obstacle-middle", asset: "/assets/kenney/mini-skate/obstacle-middle.glb", name: "Mini Skate: Middle" },
  { slug: "mini-skate-pallet", asset: "/assets/kenney/mini-skate/pallet.glb", name: "Mini Skate: Pallet" },
  { slug: "mini-skate-rail-curve", asset: "/assets/kenney/mini-skate/rail-curve.glb", name: "Mini Skate: Curve" },
  { slug: "mini-skate-rail-high", asset: "/assets/kenney/mini-skate/rail-high.glb", name: "Mini Skate: High" },
  { slug: "mini-skate-rail-low", asset: "/assets/kenney/mini-skate/rail-low.glb", name: "Mini Skate: Low" },
  { slug: "mini-skate-rail-slope", asset: "/assets/kenney/mini-skate/rail-slope.glb", name: "Mini Skate: Slope" },
  { slug: "mini-skate-skateboard", asset: "/assets/kenney/mini-skate/skateboard.glb", name: "Mini Skate: Skateboard" },
  { slug: "mini-skate-steps", asset: "/assets/kenney/mini-skate/steps.glb", name: "Mini Skate: Steps" },
  { slug: "mini-skate-structure-platform", asset: "/assets/kenney/mini-skate/structure-platform.glb", name: "Mini Skate: Platform" },
  { slug: "mini-skate-structure-wood", asset: "/assets/kenney/mini-skate/structure-wood.glb", name: "Mini Skate: Wood" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
