// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 26 character entries from assets/kenney/mini-characters.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "mini-char-aid-cane-blind", asset: "/assets/kenney/mini-characters/aid-cane-blind.glb", name: "Mini Char: Cane-Blind" },
  { slug: "mini-char-aid-cane-low-vision", asset: "/assets/kenney/mini-characters/aid-cane-low-vision.glb", name: "Mini Char: Cane-Low-Vision" },
  { slug: "mini-char-aid-cane", asset: "/assets/kenney/mini-characters/aid-cane.glb", name: "Mini Char: Cane" },
  { slug: "mini-char-aid-crutch", asset: "/assets/kenney/mini-characters/aid-crutch.glb", name: "Mini Char: Crutch" },
  { slug: "mini-char-aid-defibrillator-green", asset: "/assets/kenney/mini-characters/aid-defibrillator-green.glb", name: "Mini Char: Defibrillator-Green" },
  { slug: "mini-char-aid-defibrillator-red", asset: "/assets/kenney/mini-characters/aid-defibrillator-red.glb", name: "Mini Char: Defibrillator-Red" },
  { slug: "mini-char-aid-glasses", asset: "/assets/kenney/mini-characters/aid-glasses.glb", name: "Mini Char: Glasses" },
  { slug: "mini-char-aid-mask", asset: "/assets/kenney/mini-characters/aid-mask.glb", name: "Mini Char: Mask" },
  { slug: "mini-char-aid-sunglasses", asset: "/assets/kenney/mini-characters/aid-sunglasses.glb", name: "Mini Char: Sunglasses" },
  { slug: "mini-char-aid_hearing", asset: "/assets/kenney/mini-characters/aid_hearing.glb", name: "Mini Char: Aid Hearing" },
  { slug: "mini-char-character-female-a", asset: "/assets/kenney/mini-characters/character-female-a.glb", name: "Mini Char: Female-A" },
  { slug: "mini-char-character-female-b", asset: "/assets/kenney/mini-characters/character-female-b.glb", name: "Mini Char: Female-B" },
  { slug: "mini-char-character-female-c", asset: "/assets/kenney/mini-characters/character-female-c.glb", name: "Mini Char: Female-C" },
  { slug: "mini-char-character-female-d", asset: "/assets/kenney/mini-characters/character-female-d.glb", name: "Mini Char: Female-D" },
  { slug: "mini-char-character-female-e", asset: "/assets/kenney/mini-characters/character-female-e.glb", name: "Mini Char: Female-E" },
  { slug: "mini-char-character-female-f", asset: "/assets/kenney/mini-characters/character-female-f.glb", name: "Mini Char: Female-F" },
  { slug: "mini-char-character-male-a", asset: "/assets/kenney/mini-characters/character-male-a.glb", name: "Mini Char: Male-A" },
  { slug: "mini-char-character-male-b", asset: "/assets/kenney/mini-characters/character-male-b.glb", name: "Mini Char: Male-B" },
  { slug: "mini-char-character-male-c", asset: "/assets/kenney/mini-characters/character-male-c.glb", name: "Mini Char: Male-C" },
  { slug: "mini-char-character-male-d", asset: "/assets/kenney/mini-characters/character-male-d.glb", name: "Mini Char: Male-D" },
  { slug: "mini-char-character-male-e", asset: "/assets/kenney/mini-characters/character-male-e.glb", name: "Mini Char: Male-E" },
  { slug: "mini-char-character-male-f", asset: "/assets/kenney/mini-characters/character-male-f.glb", name: "Mini Char: Male-F" },
  { slug: "mini-char-wheelchair-deluxe", asset: "/assets/kenney/mini-characters/wheelchair-deluxe.glb", name: "Mini Char: Deluxe" },
  { slug: "mini-char-wheelchair-power-deluxe", asset: "/assets/kenney/mini-characters/wheelchair-power-deluxe.glb", name: "Mini Char: Power-Deluxe" },
  { slug: "mini-char-wheelchair-power", asset: "/assets/kenney/mini-characters/wheelchair-power.glb", name: "Mini Char: Power" },
  { slug: "mini-char-wheelchair", asset: "/assets/kenney/mini-characters/wheelchair.glb", name: "Mini Char: Wheelchair" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
