// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 52 character entries from assets/quaternius/cute_fish_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-fish-cute-anglerfish", asset: "/assets/quaternius/cute_fish_pack/anglerfish.glb", name: "Quat Cute Fish: Anglerfish" },
  { slug: "quat-fish-cute-armoredcatfish", asset: "/assets/quaternius/cute_fish_pack/armoredcatfish.glb", name: "Quat Cute Fish: Armoredcatfish" },
  { slug: "quat-fish-cute-betta", asset: "/assets/quaternius/cute_fish_pack/betta.glb", name: "Quat Cute Fish: Betta" },
  { slug: "quat-fish-cute-blacklionfish", asset: "/assets/quaternius/cute_fish_pack/blacklionfish.glb", name: "Quat Cute Fish: Blacklionfish" },
  { slug: "quat-fish-cute-blobfish", asset: "/assets/quaternius/cute_fish_pack/blobfish.glb", name: "Quat Cute Fish: Blobfish" },
  { slug: "quat-fish-cute-bluegoldfish", asset: "/assets/quaternius/cute_fish_pack/bluegoldfish.glb", name: "Quat Cute Fish: Bluegoldfish" },
  { slug: "quat-fish-cute-bluetang", asset: "/assets/quaternius/cute_fish_pack/bluetang.glb", name: "Quat Cute Fish: Bluetang" },
  { slug: "quat-fish-cute-boat", asset: "/assets/quaternius/cute_fish_pack/boat.glb", name: "Quat Cute Fish: Boat" },
  { slug: "quat-fish-cute-butterflyfish", asset: "/assets/quaternius/cute_fish_pack/butterflyfish.glb", name: "Quat Cute Fish: Butterflyfish" },
  { slug: "quat-fish-cute-cardinalfish", asset: "/assets/quaternius/cute_fish_pack/cardinalfish.glb", name: "Quat Cute Fish: Cardinalfish" },
  { slug: "quat-fish-cute-clownfish", asset: "/assets/quaternius/cute_fish_pack/clownfish.glb", name: "Quat Cute Fish: Clownfish" },
  { slug: "quat-fish-cute-coralgrouper", asset: "/assets/quaternius/cute_fish_pack/coralgrouper.glb", name: "Quat Cute Fish: Coralgrouper" },
  { slug: "quat-fish-cute-cowfish", asset: "/assets/quaternius/cute_fish_pack/cowfish.glb", name: "Quat Cute Fish: Cowfish" },
  { slug: "quat-fish-cute-dock_long", asset: "/assets/quaternius/cute_fish_pack/dock_long.glb", name: "Quat Cute Fish: Dock Long" },
  { slug: "quat-fish-cute-dock_long_norope", asset: "/assets/quaternius/cute_fish_pack/dock_long_norope.glb", name: "Quat Cute Fish: Dock Long Norope" },
  { slug: "quat-fish-cute-dock_stairs", asset: "/assets/quaternius/cute_fish_pack/dock_stairs.glb", name: "Quat Cute Fish: Dock Stairs" },
  { slug: "quat-fish-cute-dock_wide", asset: "/assets/quaternius/cute_fish_pack/dock_wide.glb", name: "Quat Cute Fish: Dock Wide" },
  { slug: "quat-fish-cute-fishingrod_lvl1", asset: "/assets/quaternius/cute_fish_pack/fishingrod_lvl1.glb", name: "Quat Cute Fish: Fishingrod Lvl1" },
  { slug: "quat-fish-cute-fishingrod_lvl2", asset: "/assets/quaternius/cute_fish_pack/fishingrod_lvl2.glb", name: "Quat Cute Fish: Fishingrod Lvl2" },
  { slug: "quat-fish-cute-fishingrod_lvl3", asset: "/assets/quaternius/cute_fish_pack/fishingrod_lvl3.glb", name: "Quat Cute Fish: Fishingrod Lvl3" },
  { slug: "quat-fish-cute-fishingrod_lvl4", asset: "/assets/quaternius/cute_fish_pack/fishingrod_lvl4.glb", name: "Quat Cute Fish: Fishingrod Lvl4" },
  { slug: "quat-fish-cute-fishingrod_lvl5", asset: "/assets/quaternius/cute_fish_pack/fishingrod_lvl5.glb", name: "Quat Cute Fish: Fishingrod Lvl5" },
  { slug: "quat-fish-cute-flatfish", asset: "/assets/quaternius/cute_fish_pack/flatfish.glb", name: "Quat Cute Fish: Flatfish" },
  { slug: "quat-fish-cute-flowerhorn", asset: "/assets/quaternius/cute_fish_pack/flowerhorn.glb", name: "Quat Cute Fish: Flowerhorn" },
  { slug: "quat-fish-cute-goblinshark", asset: "/assets/quaternius/cute_fish_pack/goblinshark.glb", name: "Quat Cute Fish: Goblinshark" },
  { slug: "quat-fish-cute-goldfish", asset: "/assets/quaternius/cute_fish_pack/goldfish.glb", name: "Quat Cute Fish: Goldfish" },
  { slug: "quat-fish-cute-humphead", asset: "/assets/quaternius/cute_fish_pack/humphead.glb", name: "Quat Cute Fish: Humphead" },
  { slug: "quat-fish-cute-koi", asset: "/assets/quaternius/cute_fish_pack/koi.glb", name: "Quat Cute Fish: Koi" },
  { slug: "quat-fish-cute-lionfish", asset: "/assets/quaternius/cute_fish_pack/lionfish.glb", name: "Quat Cute Fish: Lionfish" },
  { slug: "quat-fish-cute-lure_1", asset: "/assets/quaternius/cute_fish_pack/lure_1.glb", name: "Quat Cute Fish: Lure 1" },
  { slug: "quat-fish-cute-lure_2", asset: "/assets/quaternius/cute_fish_pack/lure_2.glb", name: "Quat Cute Fish: Lure 2" },
  { slug: "quat-fish-cute-lure_3", asset: "/assets/quaternius/cute_fish_pack/lure_3.glb", name: "Quat Cute Fish: Lure 3" },
  { slug: "quat-fish-cute-lure_4", asset: "/assets/quaternius/cute_fish_pack/lure_4.glb", name: "Quat Cute Fish: Lure 4" },
  { slug: "quat-fish-cute-lure_5", asset: "/assets/quaternius/cute_fish_pack/lure_5.glb", name: "Quat Cute Fish: Lure 5" },
  { slug: "quat-fish-cute-lure_6", asset: "/assets/quaternius/cute_fish_pack/lure_6.glb", name: "Quat Cute Fish: Lure 6" },
  { slug: "quat-fish-cute-mandarinfish", asset: "/assets/quaternius/cute_fish_pack/mandarinfish.glb", name: "Quat Cute Fish: Mandarinfish" },
  { slug: "quat-fish-cute-moorishidol", asset: "/assets/quaternius/cute_fish_pack/moorishidol.glb", name: "Quat Cute Fish: Moorishidol" },
  { slug: "quat-fish-cute-parrotfish", asset: "/assets/quaternius/cute_fish_pack/parrotfish.glb", name: "Quat Cute Fish: Parrotfish" },
  { slug: "quat-fish-cute-piranha", asset: "/assets/quaternius/cute_fish_pack/piranha.glb", name: "Quat Cute Fish: Piranha" },
  { slug: "quat-fish-cute-puffer", asset: "/assets/quaternius/cute_fish_pack/puffer.glb", name: "Quat Cute Fish: Puffer" },
  { slug: "quat-fish-cute-redsnapper", asset: "/assets/quaternius/cute_fish_pack/redsnapper.glb", name: "Quat Cute Fish: Redsnapper" },
  { slug: "quat-fish-cute-royalgramma", asset: "/assets/quaternius/cute_fish_pack/royalgramma.glb", name: "Quat Cute Fish: Royalgramma" },
  { slug: "quat-fish-cute-shark", asset: "/assets/quaternius/cute_fish_pack/shark.glb", name: "Quat Cute Fish: Shark" },
  { slug: "quat-fish-cute-sunfish", asset: "/assets/quaternius/cute_fish_pack/sunfish.glb", name: "Quat Cute Fish: Sunfish" },
  { slug: "quat-fish-cute-swordfish", asset: "/assets/quaternius/cute_fish_pack/swordfish.glb", name: "Quat Cute Fish: Swordfish" },
  { slug: "quat-fish-cute-tang", asset: "/assets/quaternius/cute_fish_pack/tang.glb", name: "Quat Cute Fish: Tang" },
  { slug: "quat-fish-cute-tetra", asset: "/assets/quaternius/cute_fish_pack/tetra.glb", name: "Quat Cute Fish: Tetra" },
  { slug: "quat-fish-cute-tuna", asset: "/assets/quaternius/cute_fish_pack/tuna.glb", name: "Quat Cute Fish: Tuna" },
  { slug: "quat-fish-cute-turbot", asset: "/assets/quaternius/cute_fish_pack/turbot.glb", name: "Quat Cute Fish: Turbot" },
  { slug: "quat-fish-cute-worm", asset: "/assets/quaternius/cute_fish_pack/worm.glb", name: "Quat Cute Fish: Worm" },
  { slug: "quat-fish-cute-yellowtang", asset: "/assets/quaternius/cute_fish_pack/yellowtang.glb", name: "Quat Cute Fish: Yellowtang" },
  { slug: "quat-fish-cute-zebraclownfish", asset: "/assets/quaternius/cute_fish_pack/zebraclownfish.glb", name: "Quat Cute Fish: Zebraclownfish" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
