/**
 * WBS: Per-Screen Vertical Pipeline, branched on htmlReference (v2)
 *
 * Level 1: One parent task per screen.
 * Level 2: 7 sequential step tasks per screen, chosen from one of two pipelines:
 *
 *   with-reference (htmlReference non-empty + file exists):
 *     01-link-reference → 02-normalize-to-glossary → 03-convert →
 *     04-analyze → 05-split → 06-lift → 07-states
 *
 *   without-reference:
 *     01-spec → 02-design → 03-convert →
 *     04-analyze → 05-split → 06-lift → 07-states
 *
 * Overlays (route starts with "overlay:") are skipped here — phase 07 handles them.
 *
 * Screens run sequentially: each screen's 07-states blocks the next screen's first step.
 */

import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

import { toPascalCase, toSnakeCase, routeToScreenPath, routeToWidgetsDir } from './helpers.js';

const TEMPLATE_ROOT = '.converge/playbooks/default/tasks/03-build-screens/wbs/templates';

export async function run(ctx) {
  const screensPath = join(ctx.projectDir, '.stitch/screens.json');

  if (!existsSync(screensPath)) {
    throw new Error(
      `Missing required file: .stitch/screens.json\n` +
      `This file should be generated by task '005-derive-screens-json' in epic 01-prepare-requirements.`
    );
  }

  const raw = JSON.parse(readFileSync(screensPath, 'utf-8'));
  const all = Array.isArray(raw) ? raw : raw.screens;

  // Filter out overlays — they're handled by phase 07-build-overlays.
  const screens = all.filter(s =>
    typeof s.route === 'string' &&
    s.route.startsWith('/') &&
    !s.route.startsWith('overlay:')
  );

  if (!screens.length) {
    throw new Error('screens.json has no non-overlay screens with a "/" route');
  }

  let prevScreenLastId = null;

  for (let idx = 0; idx < screens.length; idx++) {
    const screen = screens[idx];
    const { id: screenId, title, route } = screen;
    const prefix = String(idx + 1).padStart(3, '0');
    const widgetName = toPascalCase(screenId);
    const snakeName = toSnakeCase(screenId);
    const screenPath = routeToScreenPath(route, screenId);
    const widgetsJsonPath = `.stitch/designs/${screenId}/widgets.jsonl`;
    const localWidgetsDir = routeToWidgetsDir(screenId);
    const screenTaskId = `${prefix}-${screenId}`;

    // Resolve htmlReference — trim, check file presence.
    const rawHtmlRef = typeof screen.htmlReference === 'string' ? screen.htmlReference.trim() : '';
    const hasReference = rawHtmlRef && existsSync(join(ctx.projectDir, rawHtmlRef));
    if (rawHtmlRef && !hasReference) {
      ctx.log.warn(`screen ${screenId}: htmlReference "${rawHtmlRef}" does not exist; falling back to without-reference pipeline`);
    }

    const rawShotRef = typeof screen.screenshotReference === 'string' ? screen.screenshotReference.trim() : '';
    const screenshotReference = rawShotRef && existsSync(join(ctx.projectDir, rawShotRef)) ? rawShotRef : '';

    const vars = {
      prefix,
      screenId,
      title,
      widgetName,
      snakeName,
      route,
      screenPath,
      widgetsJsonPath,
      localWidgetsDir,
      screenTaskId,
      specPath: `.stitch/designs/${screenId}/SPEC.md`,
      metaPath: `.stitch/designs/${screenId}/META.md`,
      designPath: `.stitch/designs/${screenId}/design.html`,
      linkedHtmlPath: `.stitch/designs/${screenId}/code.html`,
      statesPath: `lib/screens/${snakeName}/${snakeName}_states.dart`,
      htmlReference: rawHtmlRef,
      htmlReferenceInput: rawHtmlRef ? `  - "${rawHtmlRef.replace(/"/g, '\\"')}"\n` : '',
      screenshotReference,
      screenshotReferenceInput: screenshotReference ? `  - "${screenshotReference.replace(/"/g, '\\"')}"\n` : '',
      prevScreenLastId: prevScreenLastId || '',
      variant: typeof screen.variant === 'string' ? screen.variant : '',
      variantGroup: typeof screen.variantGroup === 'string' ? screen.variantGroup : '',
    };

    // ── Level 1: Screen parent task ──────────────────────────────────────
    await ctx.spawn({
      id: screenTaskId,
      title: `Screen: ${title}`,
      dependencies: prevScreenLastId ? [prevScreenLastId] : [],
      tags: ['screen', `screen-${screenId}`, hasReference ? 'has-reference' : 'no-reference'],
      vars: { screenId, screenTitle: title, widgetName, route, hasReference: String(hasReference) },
      inputs: [
        '.stitch/screens.json',
        '.stitch/system/DESIGN.md',
        '.stitch/system/tokens.json',
        '.stitch/UX.md',
        ...(hasReference ? [rawHtmlRef] : []),
        ...(screenshotReference ? [screenshotReference] : []),
      ],
      outputs: [screenPath, vars.statesPath],
      body: `Parent task for building the "${title}" screen.\n\n` +
            `Pipeline: ${hasReference ? 'with-reference (link → normalize → convert → analyze → split → lift → states)' : 'without-reference (spec → design → convert → analyze → split → lift → states)'}.\n` +
            (hasReference ? `\nReference HTML: \`${rawHtmlRef}\`.\n` : '') +
            (screenshotReference ? `Reference screenshot: \`${screenshotReference}\`.\n` : ''),
    });

    // ── Level 2: Step children ───────────────────────────────────────────
    const pipelineDir = hasReference ? 'screen-with-reference' : 'screen-without-reference';
    const templateBase = `${TEMPLATE_ROOT}/${pipelineDir}`;

    const steps = hasReference
      ? ['01-link-reference', '02-normalize-to-glossary', '03-convert', '04-analyze', '05-split', '06-lift', '07-states']
      : ['01-spec', '02-design', '03-convert', '04-analyze', '05-split', '06-lift', '07-states'];

    const basePath = `.converge/playbooks/default/tasks/03-build-screens/tasks/${screenTaskId}`;

    for (const step of steps) {
      const id = `${prefix}-${step}`;
      const templatePath = `${templateBase}/tasks/{{prefix}}-${step}/TASK.md`;
      const writeToPath = `${basePath}/tasks/${id}/TASK.md`;

      await ctx.spawn(
        { _type: 'template-ref', path: templatePath, vars },
        { id, writeToPath }
      );
    }

    prevScreenLastId = `${prefix}-07-states`;
  }
}
