// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 24 character entries from assets/kenney/cube-pets.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "cube-pet-animal-beaver", asset: "/assets/kenney/cube-pets/animal-beaver.glb", name: "Cube Pet: Beaver" },
  { slug: "cube-pet-animal-bee", asset: "/assets/kenney/cube-pets/animal-bee.glb", name: "Cube Pet: Bee" },
  { slug: "cube-pet-animal-bunny", asset: "/assets/kenney/cube-pets/animal-bunny.glb", name: "Cube Pet: Bunny" },
  { slug: "cube-pet-animal-cat", asset: "/assets/kenney/cube-pets/animal-cat.glb", name: "Cube Pet: Cat" },
  { slug: "cube-pet-animal-caterpillar", asset: "/assets/kenney/cube-pets/animal-caterpillar.glb", name: "Cube Pet: Caterpillar" },
  { slug: "cube-pet-animal-chick", asset: "/assets/kenney/cube-pets/animal-chick.glb", name: "Cube Pet: Chick" },
  { slug: "cube-pet-animal-cow", asset: "/assets/kenney/cube-pets/animal-cow.glb", name: "Cube Pet: Cow" },
  { slug: "cube-pet-animal-crab", asset: "/assets/kenney/cube-pets/animal-crab.glb", name: "Cube Pet: Crab" },
  { slug: "cube-pet-animal-deer", asset: "/assets/kenney/cube-pets/animal-deer.glb", name: "Cube Pet: Deer" },
  { slug: "cube-pet-animal-dog", asset: "/assets/kenney/cube-pets/animal-dog.glb", name: "Cube Pet: Dog" },
  { slug: "cube-pet-animal-elephant", asset: "/assets/kenney/cube-pets/animal-elephant.glb", name: "Cube Pet: Elephant" },
  { slug: "cube-pet-animal-fish", asset: "/assets/kenney/cube-pets/animal-fish.glb", name: "Cube Pet: Fish" },
  { slug: "cube-pet-animal-fox", asset: "/assets/kenney/cube-pets/animal-fox.glb", name: "Cube Pet: Fox" },
  { slug: "cube-pet-animal-giraffe", asset: "/assets/kenney/cube-pets/animal-giraffe.glb", name: "Cube Pet: Giraffe" },
  { slug: "cube-pet-animal-hog", asset: "/assets/kenney/cube-pets/animal-hog.glb", name: "Cube Pet: Hog" },
  { slug: "cube-pet-animal-koala", asset: "/assets/kenney/cube-pets/animal-koala.glb", name: "Cube Pet: Koala" },
  { slug: "cube-pet-animal-lion", asset: "/assets/kenney/cube-pets/animal-lion.glb", name: "Cube Pet: Lion" },
  { slug: "cube-pet-animal-monkey", asset: "/assets/kenney/cube-pets/animal-monkey.glb", name: "Cube Pet: Monkey" },
  { slug: "cube-pet-animal-panda", asset: "/assets/kenney/cube-pets/animal-panda.glb", name: "Cube Pet: Panda" },
  { slug: "cube-pet-animal-parrot", asset: "/assets/kenney/cube-pets/animal-parrot.glb", name: "Cube Pet: Parrot" },
  { slug: "cube-pet-animal-penguin", asset: "/assets/kenney/cube-pets/animal-penguin.glb", name: "Cube Pet: Penguin" },
  { slug: "cube-pet-animal-pig", asset: "/assets/kenney/cube-pets/animal-pig.glb", name: "Cube Pet: Pig" },
  { slug: "cube-pet-animal-polar", asset: "/assets/kenney/cube-pets/animal-polar.glb", name: "Cube Pet: Polar" },
  { slug: "cube-pet-animal-tiger", asset: "/assets/kenney/cube-pets/animal-tiger.glb", name: "Cube Pet: Tiger" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
