// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 24 prop entries from assets/quaternius/medieval_weapons_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-weapon-arrow", asset: "/assets/quaternius/medieval_weapons_pack/arrow.glb", name: "Quat Weapon: Arrow" },
  { slug: "quat-weapon-axe", asset: "/assets/quaternius/medieval_weapons_pack/axe.glb", name: "Quat Weapon: Axe" },
  { slug: "quat-weapon-axe_double", asset: "/assets/quaternius/medieval_weapons_pack/axe_double.glb", name: "Quat Weapon: Axe Double" },
  { slug: "quat-weapon-axe_small", asset: "/assets/quaternius/medieval_weapons_pack/axe_small.glb", name: "Quat Weapon: Axe Small" },
  { slug: "quat-weapon-bow_evil", asset: "/assets/quaternius/medieval_weapons_pack/bow_evil.glb", name: "Quat Weapon: Bow Evil" },
  { slug: "quat-weapon-bow_golden", asset: "/assets/quaternius/medieval_weapons_pack/bow_golden.glb", name: "Quat Weapon: Bow Golden" },
  { slug: "quat-weapon-bow_wooden", asset: "/assets/quaternius/medieval_weapons_pack/bow_wooden.glb", name: "Quat Weapon: Bow Wooden" },
  { slug: "quat-weapon-bow_wooden2", asset: "/assets/quaternius/medieval_weapons_pack/bow_wooden2.glb", name: "Quat Weapon: Bow Wooden2" },
  { slug: "quat-weapon-claymore", asset: "/assets/quaternius/medieval_weapons_pack/claymore.glb", name: "Quat Weapon: Claymore" },
  { slug: "quat-weapon-dagger", asset: "/assets/quaternius/medieval_weapons_pack/dagger.glb", name: "Quat Weapon: Dagger" },
  { slug: "quat-weapon-dagger_2", asset: "/assets/quaternius/medieval_weapons_pack/dagger_2.glb", name: "Quat Weapon: Dagger 2" },
  { slug: "quat-weapon-hammer_double", asset: "/assets/quaternius/medieval_weapons_pack/hammer_double.glb", name: "Quat Weapon: Hammer Double" },
  { slug: "quat-weapon-hammer_small", asset: "/assets/quaternius/medieval_weapons_pack/hammer_small.glb", name: "Quat Weapon: Hammer Small" },
  { slug: "quat-weapon-scythe", asset: "/assets/quaternius/medieval_weapons_pack/scythe.glb", name: "Quat Weapon: Scythe" },
  { slug: "quat-weapon-shield_celtic_golden", asset: "/assets/quaternius/medieval_weapons_pack/shield_celtic_golden.glb", name: "Quat Weapon: Shield Celtic Golden" },
  { slug: "quat-weapon-shield_heater", asset: "/assets/quaternius/medieval_weapons_pack/shield_heater.glb", name: "Quat Weapon: Shield Heater" },
  { slug: "quat-weapon-shield_heater_2", asset: "/assets/quaternius/medieval_weapons_pack/shield_heater_2.glb", name: "Quat Weapon: Shield Heater 2" },
  { slug: "quat-weapon-shield_round", asset: "/assets/quaternius/medieval_weapons_pack/shield_round.glb", name: "Quat Weapon: Shield Round" },
  { slug: "quat-weapon-shield_round_2", asset: "/assets/quaternius/medieval_weapons_pack/shield_round_2.glb", name: "Quat Weapon: Shield Round 2" },
  { slug: "quat-weapon-spear", asset: "/assets/quaternius/medieval_weapons_pack/spear.glb", name: "Quat Weapon: Spear" },
  { slug: "quat-weapon-sword", asset: "/assets/quaternius/medieval_weapons_pack/sword.glb", name: "Quat Weapon: Sword" },
  { slug: "quat-weapon-sword_2", asset: "/assets/quaternius/medieval_weapons_pack/sword_2.glb", name: "Quat Weapon: Sword 2" },
  { slug: "quat-weapon-sword_big", asset: "/assets/quaternius/medieval_weapons_pack/sword_big.glb", name: "Quat Weapon: Sword Big" },
  { slug: "quat-weapon-sword_golden", asset: "/assets/quaternius/medieval_weapons_pack/sword_golden.glb", name: "Quat Weapon: Sword Golden" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
