/**
 * WBS: One task per example in docs/_examples.json.
 *
 * Reads the manifest produced by 02-source-scan, spawns a per-example
 * task that instantiates the example-page template with substitution
 * vars: slug, title, category, readmePath, playbookPath, tagline,
 * complexity, hasReadme, hasPlaybook, pagePath.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const TEMPLATE_ROOT =
  '.converge/playbooks/generate-docs/seeds/examples/templates';

const VALID_CATEGORIES = new Set([
  'learning',
  'software',
  'research',
  'creative',
  'security',
  'agent-protocol',
]);

export async function run(ctx) {
  const manifestPath = join(ctx.projectDir, 'docs/_examples.json');
  if (!existsSync(manifestPath)) {
    throw new Error(
      'Missing docs/_examples.json. ' +
        'It should have been generated by 02-source-scan.',
    );
  }

  const examples = JSON.parse(readFileSync(manifestPath, 'utf-8'));
  if (!Array.isArray(examples) || examples.length === 0) {
    throw new Error('docs/_examples.json has no entries');
  }

  // Sort by category then slug for stable spawn order.
  const sorted = [...examples].sort((a, b) => {
    const ca = String(a.category || 'unknown');
    const cb = String(b.category || 'unknown');
    if (ca !== cb) return ca.localeCompare(cb);
    return String(a.slug).localeCompare(String(b.slug));
  });

  for (let idx = 0; idx < sorted.length; idx++) {
    const ex = sorted[idx];
    if (!ex.slug) continue;

    const category = VALID_CATEGORIES.has(ex.category)
      ? ex.category
      : 'learning';

    const prefix = String(idx + 1).padStart(3, '0');
    const slug = String(ex.slug).replace(/[^a-z0-9-]/gi, '-').toLowerCase();
    const taskId = `${prefix}-${slug}`;

    const vars = {
      prefix,
      slug,
      title: ex.title || slug,
      category,
      tagline: ex.tagline || '',
      complexity: ex.complexity || 'unknown',
      readmePath: ex.readmePath || '',
      playbookPath: ex.playbookPath || '',
      hasReadme: ex.hasReadme === true ? 'true' : 'false',
      hasPlaybook: ex.hasPlaybook === true ? 'true' : 'false',
      pagePath: `docs/examples/${category}/${slug}.md`,
    };

    const templatePath = `${TEMPLATE_ROOT}/example-page/tasks/{{slug}}/TASK.md`;
    await ctx.spawn(
      { _type: 'template-ref', path: templatePath, vars },
      { id: taskId },
    );
  }
}
