/**
 * RFC 0024 — Stray-file detectors.
 *
 * Two locks the principle requires:
 *
 *   - The body never writes its own `spawn.plan.jsonl`. The internal
 *     manifest is regenerated by the framework on every apply from the
 *     discovered `spawn.yml` files.
 *   - The body never writes a child's own `TASK.md`. Contracts live in
 *     templates; the body's job is to *invoke* contracts, not author them.
 *
 * Both checks run on the post-body scan of the spawn cwd. Violations
 * become per-file evidence rows that surface in STATUS.md and block
 * apply.
 */
import {
  existsSync,
  readdirSync,
  statSync,
} from "node:fs";
import { join } from "node:path";
import type { SpawnFileEvidence } from "./discover.ts";

export function detectStrayManifests(spawnRoot: string): SpawnFileEvidence[] {
  if (!existsSync(spawnRoot)) return [];
  const stray = join(spawnRoot, "spawn.plan.jsonl");
  if (!existsSync(stray)) return [];
  return [
    {
      id: "<spawn-root>",
      file: "spawn.plan.jsonl",
      errorCode: "SPAWN_MANIFEST_AUTHORED_BY_BODY",
      message:
        "the body wrote `spawn.plan.jsonl` directly. The manifest is framework-internal — invoke templates via `<id>/spawn.yml` instead.",
      fix: "delete `spawn.plan.jsonl`; for each row you'd have written, create `<id>/spawn.yml` with `template:` and `params:`.",
    },
  ];
}

export function detectStrayTaskMd(spawnRoot: string): SpawnFileEvidence[] {
  if (!existsSync(spawnRoot)) return [];
  const out: SpawnFileEvidence[] = [];
  let entries: string[];
  try {
    entries = readdirSync(spawnRoot);
  } catch {
    return out;
  }

  for (const name of entries) {
    if (name.startsWith("_")) continue;
    const dir = join(spawnRoot, name);
    let st;
    try {
      st = statSync(dir);
    } catch {
      continue;
    }
    if (!st.isDirectory()) continue;
    const taskMd = join(dir, "TASK.md");
    if (!existsSync(taskMd)) continue;
    out.push({
      id: name,
      file: `${name}/TASK.md`,
      errorCode: "SPAWN_TASKMD_AUTHORED_BY_BODY",
      message: `the body wrote \`${name}/TASK.md\` directly. Contracts live in templates — invoke them via \`${name}/spawn.yml\`.`,
      fix: `delete \`${name}/TASK.md\`; pick a template under \`templates/\` and write \`${name}/spawn.yml\` with \`template:\` and \`params:\``,
    });
  }
  return out;
}
