// Meshy AI Fox — multi-state animation. Built on top of the single baked
// 'baselayer' walk clip Meshy generated by:
//   1. Time-scaling the clip (0 = freeze, 1 = walk, 2.4 = run)
//   2. Crossfading the clip's effective weight (0 = T-pose; useful for
//      "Sit" or "Sleep" where leg motion shouldn't show)
//   3. Per-bone procedural overlays (sine waves on head, tail, Hips)
//      added on top of the mixer pose for breath, wag, head-bob, etc.
//   4. Root-pose tilts + lowers for body posture (Sit tilts back, Sleep
//      lowers and rolls slightly).
//
// Six states, 4-second dwell each, 0.6s crossfade:
//   Idle → Walk → Run → Pant → Sit → Sleep → loop
//
// This is procedural fakery, not real animation authoring. It works
// because the underlying GLB ships with one good walk cycle we can
// distort. For richer motion you'd ship more clips from Meshy or
// retarget Quaternius's 12 fox clips onto this rig (left as exercise).

import {
  GltfModelMultiState, widgetToAssetModule,
} from '@lego';
import type { AnimState } from '@lego';

const STATES: AnimState[] = [
  {
    name: 'Idle',
    timeScale: 0.15,
    weight: 0.4,
    overlays: [
      { bone: 'head', prop: 'rotation', axis: 'y', amplitude: 0.10, freq: 0.4 },
      { bone: 'head', prop: 'rotation', axis: 'x', amplitude: 0.04, freq: 0.6, phase: 0.5 },
      { bone: 'tail2', prop: 'rotation', axis: 'y', amplitude: 0.18, freq: 0.7 },
      { bone: 'tail3', prop: 'rotation', axis: 'y', amplitude: 0.25, freq: 0.7, phase: 0.4 },
    ],
  },
  {
    name: 'Walk',
    timeScale: 1.0,
    weight: 1.0,
    overlays: [
      { bone: 'tail2', prop: 'rotation', axis: 'y', amplitude: 0.12, freq: 1.5 },
      { bone: 'tail3', prop: 'rotation', axis: 'y', amplitude: 0.18, freq: 1.5, phase: 0.5 },
    ],
  },
  {
    name: 'Run',
    timeScale: 2.4,
    weight: 1.0,
    overlays: [
      { bone: 'tail3', prop: 'rotation', axis: 'y', amplitude: 0.30, freq: 3.0 },
    ],
    rootPose: { rotationX: -0.08 },
  },
  {
    name: 'Pant',
    timeScale: 0,
    weight: 0,
    overlays: [
      { bone: 'head', prop: 'rotation', axis: 'x', amplitude: 0.18, freq: 3.0 },
      { bone: 'head', prop: 'position', axis: 'y', amplitude: 0.005, freq: 3.0 },
      { bone: 'tail2', prop: 'rotation', axis: 'y', amplitude: 0.10, freq: 1.0 },
    ],
  },
  {
    name: 'Sit',
    timeScale: 0,
    weight: 0,
    overlays: [
      { bone: 'head', prop: 'rotation', axis: 'y', amplitude: 0.15, freq: 0.5 },
      { bone: 'tail2', prop: 'rotation', axis: 'y', amplitude: 0.10, freq: 0.6 },
    ],
    rootPose: { rotationX: 0.20 },
  },
  {
    name: 'Sleep',
    timeScale: 0,
    weight: 0,
    overlays: [
      { bone: 'Hips', prop: 'position', axis: 'y', amplitude: 0.012, freq: 0.4 },
      { bone: 'chest', prop: 'rotation', axis: 'x', amplitude: 0.02, freq: 0.4, phase: 1.5 },
    ],
    rootPose: { rotationZ: 0.15 },
  },
];

export default widgetToAssetModule(
  'meshy-fox-multistate',
  {
    kind: 'character',
    archetype: 'biped',
    name: 'Meshy AI Fox (6 states)',
    description: 'Meshy auto-rigged fox cycling Idle / Walk / Run / Pant / Sit / Sleep. Six states synthesized from the single baked walk clip via timeScale, action-weight, and per-bone procedural overlays.',
  },
  new GltfModelMultiState({
    asset: '/assets/meshy/fox-rigged-walk.glb',
    baseClip: 'baselayer',
    states: STATES,
    dwell: 4.0,
    fade: 0.6,
  }),
);
