// Meshy AI Low Poly Fox — static GLB generated by Meshy.ai (text-to-3D).
// 271k triangles, single mesh, no skeleton, no animations. Useful as a
// hero showcase asset; not suitable as a game character because:
//   1. No rig → no animations possible without a separate rigging pass
//      (Mixamo doesn't auto-rig quadrupeds; would need DeepMotion or
//      manual Blender work).
//   2. 271k tris → 100× heavier than a typical game asset; 5 of these
//      in a scene would already strain a low-end device.
//
// For a production-ready animated fox, see catalog/quaternius-animals/
// (slug=quat-animal-fox) — Quaternius rigged ~2k-tri fox with 12
// baked clips (Idle, Walk, Run, Gallop, Attack, Death, Eating, etc).
//
// Side-by-side showcase: scenes/fox-showcase.ts

import { GltfModel, widgetToAssetModule } from '@lego';

export default widgetToAssetModule(
  'meshy-fox',
  {
    kind: 'character',
    archetype: 'biped',  // closest fit; we have no 'quadruped' value
    name: 'Meshy AI Fox (static)',
    description: 'Meshy.ai text-to-3D fox. 271k triangles, no rig, no animation. Showcase quality, not game-ready.',
  },
  new GltfModel({
    asset: '/assets/meshy/fox.glb',
    scale: 1.0,
    // GLB origin sits at body center (yMin=-0.95). Lift so feet rest on ground.
    position: [0, 0.95, 0],
  }),
);
