// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 20 prop entries from assets/kenney/mini-market.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "mini-market-bottle-return", asset: "/assets/kenney/mini-market/bottle-return.glb", name: "Mini Market: Return" },
  { slug: "mini-market-cash-register", asset: "/assets/kenney/mini-market/cash-register.glb", name: "Mini Market: Register" },
  { slug: "mini-market-character-employee", asset: "/assets/kenney/mini-market/character-employee.glb", name: "Mini Market: Employee" },
  { slug: "mini-market-column", asset: "/assets/kenney/mini-market/column.glb", name: "Mini Market: Column" },
  { slug: "mini-market-display-bread", asset: "/assets/kenney/mini-market/display-bread.glb", name: "Mini Market: Bread" },
  { slug: "mini-market-display-fruit", asset: "/assets/kenney/mini-market/display-fruit.glb", name: "Mini Market: Fruit" },
  { slug: "mini-market-fence-door-rotate", asset: "/assets/kenney/mini-market/fence-door-rotate.glb", name: "Mini Market: Door-Rotate" },
  { slug: "mini-market-fence", asset: "/assets/kenney/mini-market/fence.glb", name: "Mini Market: Fence" },
  { slug: "mini-market-floor", asset: "/assets/kenney/mini-market/floor.glb", name: "Mini Market: Floor" },
  { slug: "mini-market-freezer", asset: "/assets/kenney/mini-market/freezer.glb", name: "Mini Market: Freezer" },
  { slug: "mini-market-freezers-standing", asset: "/assets/kenney/mini-market/freezers-standing.glb", name: "Mini Market: Standing" },
  { slug: "mini-market-shelf-bags", asset: "/assets/kenney/mini-market/shelf-bags.glb", name: "Mini Market: Bags" },
  { slug: "mini-market-shelf-boxes", asset: "/assets/kenney/mini-market/shelf-boxes.glb", name: "Mini Market: Boxes" },
  { slug: "mini-market-shelf-end", asset: "/assets/kenney/mini-market/shelf-end.glb", name: "Mini Market: End" },
  { slug: "mini-market-shopping-basket", asset: "/assets/kenney/mini-market/shopping-basket.glb", name: "Mini Market: Basket" },
  { slug: "mini-market-shopping-cart", asset: "/assets/kenney/mini-market/shopping-cart.glb", name: "Mini Market: Cart" },
  { slug: "mini-market-wall-corner", asset: "/assets/kenney/mini-market/wall-corner.glb", name: "Mini Market: Corner" },
  { slug: "mini-market-wall-door-rotate", asset: "/assets/kenney/mini-market/wall-door-rotate.glb", name: "Mini Market: Door-Rotate" },
  { slug: "mini-market-wall-window", asset: "/assets/kenney/mini-market/wall-window.glb", name: "Mini Market: Window" },
  { slug: "mini-market-wall", asset: "/assets/kenney/mini-market/wall.glb", name: "Mini Market: Wall" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
