// Build-time generator: scans assets/{dungeon,hexagon,furniture}, writes
// catalog manifest files (one per group, multi-export). Re-run any time
// new packs are vendored.

import { readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(fileURLToPath(import.meta.url), '..', '..');

type Group = {
  /** Dir under examples/game-assets-lego/assets/ */
  dir: string;
  /** Glob extension to pick up. */
  ext: '.glb' | '.gltf';
  /** Asset kind tag for metadata. */
  kind: 'prop' | 'building' | 'character';
  /** Slug prefix to namespace this group's slugs (e.g. 'dungeon-'). */
  slugPrefix: string;
  /** Output catalog file (single .ts that exports an array of AssetModules). */
  outFile: string;
  /** Pretty-name prefix in metadata.name (e.g. 'Dungeon: '). */
  namePrefix: string;
};

const GROUPS: Group[] = [
  {
    dir: 'assets/dungeon',
    ext: '.glb',
    kind: 'prop',
    slugPrefix: 'dungeon-',
    outFile: 'catalog/dungeon/_pack.ts',
    namePrefix: 'Dungeon: ',
  },
  {
    dir: 'assets/hexagon',
    ext: '.gltf',
    kind: 'building',
    slugPrefix: 'hex-',
    outFile: 'catalog/hexagon/_pack.ts',
    namePrefix: 'Hex: ',
  },
  {
    dir: 'assets/furniture',
    ext: '.gltf',
    kind: 'prop',
    slugPrefix: 'furn-',
    outFile: 'catalog/furniture/_pack.ts',
    namePrefix: 'Furniture: ',
  },
  // Kenney Mini packs — simpler/blockier CC0 alternative to KayKit.
  {
    dir: 'assets/kenney/mini-dungeon',
    ext: '.glb',
    kind: 'prop',
    slugPrefix: 'mini-dungeon-',
    outFile: 'catalog/kenney-mini-dungeon/_pack.ts',
    namePrefix: 'Mini Dungeon: ',
  },
  {
    dir: 'assets/kenney/mini-characters',
    ext: '.glb',
    kind: 'character',
    slugPrefix: 'mini-char-',
    outFile: 'catalog/kenney-mini-characters/_pack.ts',
    namePrefix: 'Mini Char: ',
  },
  {
    dir: 'assets/kenney/mini-arena',
    ext: '.glb',
    kind: 'prop',
    slugPrefix: 'mini-arena-',
    outFile: 'catalog/kenney-mini-arena/_pack.ts',
    namePrefix: 'Mini Arena: ',
  },
  {
    dir: 'assets/kenney/mini-market',
    ext: '.glb',
    kind: 'prop',
    slugPrefix: 'mini-market-',
    outFile: 'catalog/kenney-mini-market/_pack.ts',
    namePrefix: 'Mini Market: ',
  },
  {
    dir: 'assets/kenney/mini-arcade',
    ext: '.glb',
    kind: 'prop',
    slugPrefix: 'mini-arcade-',
    outFile: 'catalog/kenney-mini-arcade/_pack.ts',
    namePrefix: 'Mini Arcade: ',
  },
  {
    dir: 'assets/kenney/mini-skate',
    ext: '.glb',
    kind: 'prop',
    slugPrefix: 'mini-skate-',
    outFile: 'catalog/kenney-mini-skate/_pack.ts',
    namePrefix: 'Mini Skate: ',
  },
  {
    dir: 'assets/kenney/cube-pets',
    ext: '.glb',
    kind: 'character',
    slugPrefix: 'cube-pet-',
    outFile: 'catalog/kenney-cube-pets/_pack.ts',
    namePrefix: 'Cube Pet: ',
  },
];

function walk(root: string, ext: string): string[] {
  const out: string[] = [];
  function recurse(p: string): void {
    for (const entry of readdirSync(p)) {
      const full = join(p, entry);
      const s = statSync(full);
      if (s.isDirectory()) recurse(full);
      else if (entry.endsWith(ext)) out.push(full);
    }
  }
  recurse(root);
  return out;
}

function prettyName(slug: string): string {
  return slug
    .replace(/^.*?-/, '') // drop pack prefix
    .replace(/_/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

for (const group of GROUPS) {
  const absDir = join(ROOT, group.dir);
  const files = walk(absDir, group.ext).sort();
  const entries: { slug: string; assetPath: string; name: string }[] = [];
  for (const f of files) {
    // assetPath = path served by Vite (relative to project root, prefixed '/')
    const relProj = relative(ROOT, f).replace(/\\/g, '/');
    const assetPath = '/' + relProj;
    // slug = pack prefix + relative path under group dir (without ext, lowercase, slashes → '-')
    const relGroup = relative(absDir, f).replace(/\\/g, '/');
    const stem = relGroup.replace(new RegExp(group.ext + '$'), '');
    const slugSuffix = stem.toLowerCase().replace(/\//g, '-').replace(/[^a-z0-9_-]/g, '-');
    const slug = group.slugPrefix + slugSuffix;
    const name = group.namePrefix + prettyName(slugSuffix);
    entries.push({ slug, assetPath, name });
  }

  // Generate the manifest file
  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.`);
  lines.push(`// ${entries.length} ${group.kind} entries from ${group.dir}.`);
  lines.push(``);
  lines.push(`import { GltfModel, widgetToAssetModule } from '@lego';`);
  lines.push(`import type { AssetModule } from '../../src/types.js';`);
  lines.push(``);
  lines.push(`interface PackEntry { slug: string; asset: string; name: string; }`);
  lines.push(``);
  lines.push(`const ENTRIES: PackEntry[] = [`);
  for (const e of entries) {
    lines.push(`  { slug: ${JSON.stringify(e.slug)}, asset: ${JSON.stringify(e.assetPath)}, name: ${JSON.stringify(e.name)} },`);
  }
  lines.push(`];`);
  lines.push(``);
  lines.push(`const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(`);
  lines.push(`  e.slug,`);
  lines.push(`  { kind: ${JSON.stringify(group.kind)}, name: e.name },`);
  lines.push(`  new GltfModel({ asset: e.asset }),`);
  lines.push(`));`);
  lines.push(``);
  lines.push(`export default modules;`);
  lines.push(``);

  const outPath = join(ROOT, group.outFile);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join('\n'));
  console.log(`wrote ${group.outFile}: ${entries.length} entries`);
}
