// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 13 prop entries from assets/quaternius/simple_nature_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-nature-simple-bush1", asset: "/assets/quaternius/simple_nature_pack/bush1.glb", name: "Quat Simple Nature: Bush1" },
  { slug: "quat-nature-simple-bush2", asset: "/assets/quaternius/simple_nature_pack/bush2.glb", name: "Quat Simple Nature: Bush2" },
  { slug: "quat-nature-simple-bush3", asset: "/assets/quaternius/simple_nature_pack/bush3.glb", name: "Quat Simple Nature: Bush3" },
  { slug: "quat-nature-simple-grass1", asset: "/assets/quaternius/simple_nature_pack/grass1.glb", name: "Quat Simple Nature: Grass1" },
  { slug: "quat-nature-simple-grass2", asset: "/assets/quaternius/simple_nature_pack/grass2.glb", name: "Quat Simple Nature: Grass2" },
  { slug: "quat-nature-simple-grass3", asset: "/assets/quaternius/simple_nature_pack/grass3.glb", name: "Quat Simple Nature: Grass3" },
  { slug: "quat-nature-simple-rock1", asset: "/assets/quaternius/simple_nature_pack/rock1.glb", name: "Quat Simple Nature: Rock1" },
  { slug: "quat-nature-simple-rock2", asset: "/assets/quaternius/simple_nature_pack/rock2.glb", name: "Quat Simple Nature: Rock2" },
  { slug: "quat-nature-simple-rock3", asset: "/assets/quaternius/simple_nature_pack/rock3.glb", name: "Quat Simple Nature: Rock3" },
  { slug: "quat-nature-simple-tree1", asset: "/assets/quaternius/simple_nature_pack/tree1.glb", name: "Quat Simple Nature: Tree1" },
  { slug: "quat-nature-simple-tree2", asset: "/assets/quaternius/simple_nature_pack/tree2.glb", name: "Quat Simple Nature: Tree2" },
  { slug: "quat-nature-simple-tree3", asset: "/assets/quaternius/simple_nature_pack/tree3.glb", name: "Quat Simple Nature: Tree3" },
  { slug: "quat-nature-simple-tree4", asset: "/assets/quaternius/simple_nature_pack/tree4.glb", name: "Quat Simple Nature: Tree4" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
