// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 6 character entries from assets/quaternius/dinosaurs_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-dino-apatosaurus", asset: "/assets/quaternius/dinosaurs_pack/apatosaurus.glb", name: "Quat Dino: Apatosaurus" },
  { slug: "quat-dino-parasaurolophus", asset: "/assets/quaternius/dinosaurs_pack/parasaurolophus.glb", name: "Quat Dino: Parasaurolophus" },
  { slug: "quat-dino-stegosaurus", asset: "/assets/quaternius/dinosaurs_pack/stegosaurus.glb", name: "Quat Dino: Stegosaurus" },
  { slug: "quat-dino-trex", asset: "/assets/quaternius/dinosaurs_pack/trex.glb", name: "Quat Dino: Trex" },
  { slug: "quat-dino-triceratops", asset: "/assets/quaternius/dinosaurs_pack/triceratops.glb", name: "Quat Dino: Triceratops" },
  { slug: "quat-dino-velociraptor", asset: "/assets/quaternius/dinosaurs_pack/velociraptor.glb", name: "Quat Dino: Velociraptor" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
