// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 53 prop entries from assets/quaternius/survival_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-survival-axe", asset: "/assets/quaternius/survival_pack/axe.glb", name: "Quat Survival: Axe" },
  { slug: "quat-survival-axe_small", asset: "/assets/quaternius/survival_pack/axe_small.glb", name: "Quat Survival: Axe Small" },
  { slug: "quat-survival-backpack", asset: "/assets/quaternius/survival_pack/backpack.glb", name: "Quat Survival: Backpack" },
  { slug: "quat-survival-bandages", asset: "/assets/quaternius/survival_pack/bandages.glb", name: "Quat Survival: Bandages" },
  { slug: "quat-survival-battery_big", asset: "/assets/quaternius/survival_pack/battery_big.glb", name: "Quat Survival: Battery Big" },
  { slug: "quat-survival-battery_small", asset: "/assets/quaternius/survival_pack/battery_small.glb", name: "Quat Survival: Battery Small" },
  { slug: "quat-survival-beartrap_closed", asset: "/assets/quaternius/survival_pack/beartrap_closed.glb", name: "Quat Survival: Beartrap Closed" },
  { slug: "quat-survival-beartrap_open", asset: "/assets/quaternius/survival_pack/beartrap_open.glb", name: "Quat Survival: Beartrap Open" },
  { slug: "quat-survival-bonfire", asset: "/assets/quaternius/survival_pack/bonfire.glb", name: "Quat Survival: Bonfire" },
  { slug: "quat-survival-bonfire_fire", asset: "/assets/quaternius/survival_pack/bonfire_fire.glb", name: "Quat Survival: Bonfire Fire" },
  { slug: "quat-survival-can_broken", asset: "/assets/quaternius/survival_pack/can_broken.glb", name: "Quat Survival: Can Broken" },
  { slug: "quat-survival-can_closed", asset: "/assets/quaternius/survival_pack/can_closed.glb", name: "Quat Survival: Can Closed" },
  { slug: "quat-survival-can_open", asset: "/assets/quaternius/survival_pack/can_open.glb", name: "Quat Survival: Can Open" },
  { slug: "quat-survival-can_red", asset: "/assets/quaternius/survival_pack/can_red.glb", name: "Quat Survival: Can Red" },
  { slug: "quat-survival-compass_closed", asset: "/assets/quaternius/survival_pack/compass_closed.glb", name: "Quat Survival: Compass Closed" },
  { slug: "quat-survival-compass_open", asset: "/assets/quaternius/survival_pack/compass_open.glb", name: "Quat Survival: Compass Open" },
  { slug: "quat-survival-firstaidkit", asset: "/assets/quaternius/survival_pack/firstaidkit.glb", name: "Quat Survival: Firstaidkit" },
  { slug: "quat-survival-firstaidkit_hard", asset: "/assets/quaternius/survival_pack/firstaidkit_hard.glb", name: "Quat Survival: Firstaidkit Hard" },
  { slug: "quat-survival-flaregun", asset: "/assets/quaternius/survival_pack/flaregun.glb", name: "Quat Survival: Flaregun" },
  { slug: "quat-survival-gascan", asset: "/assets/quaternius/survival_pack/gascan.glb", name: "Quat Survival: Gascan" },
  { slug: "quat-survival-knife", asset: "/assets/quaternius/survival_pack/knife.glb", name: "Quat Survival: Knife" },
  { slug: "quat-survival-match", asset: "/assets/quaternius/survival_pack/match.glb", name: "Quat Survival: Match" },
  { slug: "quat-survival-match_burnt", asset: "/assets/quaternius/survival_pack/match_burnt.glb", name: "Quat Survival: Match Burnt" },
  { slug: "quat-survival-match_fire", asset: "/assets/quaternius/survival_pack/match_fire.glb", name: "Quat Survival: Match Fire" },
  { slug: "quat-survival-matchbox", asset: "/assets/quaternius/survival_pack/matchbox.glb", name: "Quat Survival: Matchbox" },
  { slug: "quat-survival-pan", asset: "/assets/quaternius/survival_pack/pan.glb", name: "Quat Survival: Pan" },
  { slug: "quat-survival-pan_small", asset: "/assets/quaternius/survival_pack/pan_small.glb", name: "Quat Survival: Pan Small" },
  { slug: "quat-survival-phone", asset: "/assets/quaternius/survival_pack/phone.glb", name: "Quat Survival: Phone" },
  { slug: "quat-survival-pistol_1", asset: "/assets/quaternius/survival_pack/pistol_1.glb", name: "Quat Survival: Pistol 1" },
  { slug: "quat-survival-pistol_2", asset: "/assets/quaternius/survival_pack/pistol_2.glb", name: "Quat Survival: Pistol 2" },
  { slug: "quat-survival-pot", asset: "/assets/quaternius/survival_pack/pot.glb", name: "Quat Survival: Pot" },
  { slug: "quat-survival-pot_small", asset: "/assets/quaternius/survival_pack/pot_small.glb", name: "Quat Survival: Pot Small" },
  { slug: "quat-survival-propanetank", asset: "/assets/quaternius/survival_pack/propanetank.glb", name: "Quat Survival: Propanetank" },
  { slug: "quat-survival-radio", asset: "/assets/quaternius/survival_pack/radio.glb", name: "Quat Survival: Radio" },
  { slug: "quat-survival-raft", asset: "/assets/quaternius/survival_pack/raft.glb", name: "Quat Survival: Raft" },
  { slug: "quat-survival-raft_paddle", asset: "/assets/quaternius/survival_pack/raft_paddle.glb", name: "Quat Survival: Raft Paddle" },
  { slug: "quat-survival-revolver_1", asset: "/assets/quaternius/survival_pack/revolver_1.glb", name: "Quat Survival: Revolver 1" },
  { slug: "quat-survival-revolver_2", asset: "/assets/quaternius/survival_pack/revolver_2.glb", name: "Quat Survival: Revolver 2" },
  { slug: "quat-survival-revolver_3", asset: "/assets/quaternius/survival_pack/revolver_3.glb", name: "Quat Survival: Revolver 3" },
  { slug: "quat-survival-shotgun_1", asset: "/assets/quaternius/survival_pack/shotgun_1.glb", name: "Quat Survival: Shotgun 1" },
  { slug: "quat-survival-shotgun_2", asset: "/assets/quaternius/survival_pack/shotgun_2.glb", name: "Quat Survival: Shotgun 2" },
  { slug: "quat-survival-shotgun_sawedoff", asset: "/assets/quaternius/survival_pack/shotgun_sawedoff.glb", name: "Quat Survival: Shotgun Sawedoff" },
  { slug: "quat-survival-shotgun_shortstock", asset: "/assets/quaternius/survival_pack/shotgun_shortstock.glb", name: "Quat Survival: Shotgun Shortstock" },
  { slug: "quat-survival-shovel", asset: "/assets/quaternius/survival_pack/shovel.glb", name: "Quat Survival: Shovel" },
  { slug: "quat-survival-tent", asset: "/assets/quaternius/survival_pack/tent.glb", name: "Quat Survival: Tent" },
  { slug: "quat-survival-torch", asset: "/assets/quaternius/survival_pack/torch.glb", name: "Quat Survival: Torch" },
  { slug: "quat-survival-trashcan", asset: "/assets/quaternius/survival_pack/trashcan.glb", name: "Quat Survival: Trashcan" },
  { slug: "quat-survival-waterbottle_1", asset: "/assets/quaternius/survival_pack/waterbottle_1.glb", name: "Quat Survival: Waterbottle 1" },
  { slug: "quat-survival-waterbottle_2", asset: "/assets/quaternius/survival_pack/waterbottle_2.glb", name: "Quat Survival: Waterbottle 2" },
  { slug: "quat-survival-waterbottle_3", asset: "/assets/quaternius/survival_pack/waterbottle_3.glb", name: "Quat Survival: Waterbottle 3" },
  { slug: "quat-survival-woodentorch", asset: "/assets/quaternius/survival_pack/woodentorch.glb", name: "Quat Survival: Woodentorch" },
  { slug: "quat-survival-woodentorch_fire", asset: "/assets/quaternius/survival_pack/woodentorch_fire.glb", name: "Quat Survival: Woodentorch Fire" },
  { slug: "quat-survival-woodlog", asset: "/assets/quaternius/survival_pack/woodlog.glb", name: "Quat Survival: Woodlog" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
