// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 48 building entries from assets/quaternius/modular_dungeon_1.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-dungeon1-arch", asset: "/assets/quaternius/modular_dungeon_1/arch.glb", name: "Quat Dungeon: Arch" },
  { slug: "quat-dungeon1-arch_bars", asset: "/assets/quaternius/modular_dungeon_1/arch_bars.glb", name: "Quat Dungeon: Arch Bars" },
  { slug: "quat-dungeon1-arch_door", asset: "/assets/quaternius/modular_dungeon_1/arch_door.glb", name: "Quat Dungeon: Arch Door" },
  { slug: "quat-dungeon1-arch_door_bottompivot", asset: "/assets/quaternius/modular_dungeon_1/arch_door_bottompivot.glb", name: "Quat Dungeon: Arch Door Bottompivot" },
  { slug: "quat-dungeon1-bag_coins", asset: "/assets/quaternius/modular_dungeon_1/bag_coins.glb", name: "Quat Dungeon: Bag Coins" },
  { slug: "quat-dungeon1-bag_standing", asset: "/assets/quaternius/modular_dungeon_1/bag_standing.glb", name: "Quat Dungeon: Bag Standing" },
  { slug: "quat-dungeon1-banner", asset: "/assets/quaternius/modular_dungeon_1/banner.glb", name: "Quat Dungeon: Banner" },
  { slug: "quat-dungeon1-banner_wall", asset: "/assets/quaternius/modular_dungeon_1/banner_wall.glb", name: "Quat Dungeon: Banner Wall" },
  { slug: "quat-dungeon1-barrel", asset: "/assets/quaternius/modular_dungeon_1/barrel.glb", name: "Quat Dungeon: Barrel" },
  { slug: "quat-dungeon1-barrel2", asset: "/assets/quaternius/modular_dungeon_1/barrel2.glb", name: "Quat Dungeon: Barrel2" },
  { slug: "quat-dungeon1-brick", asset: "/assets/quaternius/modular_dungeon_1/brick.glb", name: "Quat Dungeon: Brick" },
  { slug: "quat-dungeon1-bucket", asset: "/assets/quaternius/modular_dungeon_1/bucket.glb", name: "Quat Dungeon: Bucket" },
  { slug: "quat-dungeon1-chair", asset: "/assets/quaternius/modular_dungeon_1/chair.glb", name: "Quat Dungeon: Chair" },
  { slug: "quat-dungeon1-chest", asset: "/assets/quaternius/modular_dungeon_1/chest.glb", name: "Quat Dungeon: Chest" },
  { slug: "quat-dungeon1-chest_gold", asset: "/assets/quaternius/modular_dungeon_1/chest_gold.glb", name: "Quat Dungeon: Chest Gold" },
  { slug: "quat-dungeon1-cobweb", asset: "/assets/quaternius/modular_dungeon_1/cobweb.glb", name: "Quat Dungeon: Cobweb" },
  { slug: "quat-dungeon1-cobweb2", asset: "/assets/quaternius/modular_dungeon_1/cobweb2.glb", name: "Quat Dungeon: Cobweb2" },
  { slug: "quat-dungeon1-coin_pile", asset: "/assets/quaternius/modular_dungeon_1/coin_pile.glb", name: "Quat Dungeon: Coin Pile" },
  { slug: "quat-dungeon1-column", asset: "/assets/quaternius/modular_dungeon_1/column.glb", name: "Quat Dungeon: Column" },
  { slug: "quat-dungeon1-column2", asset: "/assets/quaternius/modular_dungeon_1/column2.glb", name: "Quat Dungeon: Column2" },
  { slug: "quat-dungeon1-crate", asset: "/assets/quaternius/modular_dungeon_1/crate.glb", name: "Quat Dungeon: Crate" },
  { slug: "quat-dungeon1-decorative_wall", asset: "/assets/quaternius/modular_dungeon_1/decorative_wall.glb", name: "Quat Dungeon: Decorative Wall" },
  { slug: "quat-dungeon1-fence_90_modular", asset: "/assets/quaternius/modular_dungeon_1/fence_90_modular.glb", name: "Quat Dungeon: Fence 90 Modular" },
  { slug: "quat-dungeon1-fence_end_modular", asset: "/assets/quaternius/modular_dungeon_1/fence_end_modular.glb", name: "Quat Dungeon: Fence End Modular" },
  { slug: "quat-dungeon1-fence_straight_modular", asset: "/assets/quaternius/modular_dungeon_1/fence_straight_modular.glb", name: "Quat Dungeon: Fence Straight Modular" },
  { slug: "quat-dungeon1-floor_bricksseparate", asset: "/assets/quaternius/modular_dungeon_1/floor_bricksseparate.glb", name: "Quat Dungeon: Floor Bricksseparate" },
  { slug: "quat-dungeon1-floor_bricksseparate2", asset: "/assets/quaternius/modular_dungeon_1/floor_bricksseparate2.glb", name: "Quat Dungeon: Floor Bricksseparate2" },
  { slug: "quat-dungeon1-floor_modular", asset: "/assets/quaternius/modular_dungeon_1/floor_modular.glb", name: "Quat Dungeon: Floor Modular" },
  { slug: "quat-dungeon1-pedestal", asset: "/assets/quaternius/modular_dungeon_1/pedestal.glb", name: "Quat Dungeon: Pedestal" },
  { slug: "quat-dungeon1-pedestal2", asset: "/assets/quaternius/modular_dungeon_1/pedestal2.glb", name: "Quat Dungeon: Pedestal2" },
  { slug: "quat-dungeon1-skull", asset: "/assets/quaternius/modular_dungeon_1/skull.glb", name: "Quat Dungeon: Skull" },
  { slug: "quat-dungeon1-spikes", asset: "/assets/quaternius/modular_dungeon_1/spikes.glb", name: "Quat Dungeon: Spikes" },
  { slug: "quat-dungeon1-stairs_modular", asset: "/assets/quaternius/modular_dungeon_1/stairs_modular.glb", name: "Quat Dungeon: Stairs Modular" },
  { slug: "quat-dungeon1-stairs_sidecover", asset: "/assets/quaternius/modular_dungeon_1/stairs_sidecover.glb", name: "Quat Dungeon: Stairs Sidecover" },
  { slug: "quat-dungeon1-stairs_sidecoverwall", asset: "/assets/quaternius/modular_dungeon_1/stairs_sidecoverwall.glb", name: "Quat Dungeon: Stairs Sidecoverwall" },
  { slug: "quat-dungeon1-statue_horse", asset: "/assets/quaternius/modular_dungeon_1/statue_horse.glb", name: "Quat Dungeon: Statue Horse" },
  { slug: "quat-dungeon1-sword_wallmount", asset: "/assets/quaternius/modular_dungeon_1/sword_wallmount.glb", name: "Quat Dungeon: Sword Wallmount" },
  { slug: "quat-dungeon1-table_big", asset: "/assets/quaternius/modular_dungeon_1/table_big.glb", name: "Quat Dungeon: Table Big" },
  { slug: "quat-dungeon1-table_small", asset: "/assets/quaternius/modular_dungeon_1/table_small.glb", name: "Quat Dungeon: Table Small" },
  { slug: "quat-dungeon1-torch", asset: "/assets/quaternius/modular_dungeon_1/torch.glb", name: "Quat Dungeon: Torch" },
  { slug: "quat-dungeon1-trap_empty", asset: "/assets/quaternius/modular_dungeon_1/trap_empty.glb", name: "Quat Dungeon: Trap Empty" },
  { slug: "quat-dungeon1-trap_spikes", asset: "/assets/quaternius/modular_dungeon_1/trap_spikes.glb", name: "Quat Dungeon: Trap Spikes" },
  { slug: "quat-dungeon1-trapdoor", asset: "/assets/quaternius/modular_dungeon_1/trapdoor.glb", name: "Quat Dungeon: Trapdoor" },
  { slug: "quat-dungeon1-trapdoor_open", asset: "/assets/quaternius/modular_dungeon_1/trapdoor_open.glb", name: "Quat Dungeon: Trapdoor Open" },
  { slug: "quat-dungeon1-vase", asset: "/assets/quaternius/modular_dungeon_1/vase.glb", name: "Quat Dungeon: Vase" },
  { slug: "quat-dungeon1-wall_modular", asset: "/assets/quaternius/modular_dungeon_1/wall_modular.glb", name: "Quat Dungeon: Wall Modular" },
  { slug: "quat-dungeon1-wallcover_modular", asset: "/assets/quaternius/modular_dungeon_1/wallcover_modular.glb", name: "Quat Dungeon: Wallcover Modular" },
  { slug: "quat-dungeon1-woodfire", asset: "/assets/quaternius/modular_dungeon_1/woodfire.glb", name: "Quat Dungeon: Woodfire" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "building", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
