/**
 * WBS: Per-Section Vertical Pipeline for the Converge landing page.
 *
 * Level 1: One parent task per section (from apps/landing/.content/sections.json).
 * Level 2: 5 sequential step children per section:
 *   01-spec → 02-design → 03-build → 04-integrate → 05-verify
 *
 * Sections run sequentially: section N's 05-verify blocks section N+1's
 * 01-spec, so src/pages/index.astro stays consistent at every checkpoint.
 *
 * Templates live under seeds/per-section/templates/section/tasks/{{prefix}}-{step}/TASK.md
 * with {{placeholder}} substitution at render time.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  toPascalCase,
  toKebabCase,
  sectionComponentPath,
  sectionContentDir,
} from './per-section/helpers.js';

const TEMPLATE_ROOT =
  '.converge/playbooks/landing-page/tasks/04-build-sections/seeds/per-section/templates';

export async function run(ctx) {
  const sectionsPath = join(
    ctx.projectDir,
    'apps/landing/.content/sections.json',
  );
  if (!existsSync(sectionsPath)) {
    throw new Error(
      'Missing apps/landing/.content/sections.json. ' +
        "It should have been generated by 01-prepare-spec/002-sections-inventory.",
    );
  }

  const raw = JSON.parse(readFileSync(sectionsPath, 'utf-8'));
  const sections = Array.isArray(raw) ? raw : raw.sections;
  if (!Array.isArray(sections) || sections.length === 0) {
    throw new Error('sections.json has no sections');
  }

  let prevLastId = null;

  for (let idx = 0; idx < sections.length; idx++) {
    const s = sections[idx];
    const {
      id: sectionId,
      title,
      componentName,
      intent = '',
    } = s;
    const prefix = String(idx + 1).padStart(3, '0');
    const compName = componentName || toPascalCase(sectionId);
    const componentPath = sectionComponentPath(compName);
    const contentDir = sectionContentDir(sectionId);
    const sectionTaskId = `${prefix}-${sectionId}`;

    const vars = {
      prefix,
      sectionId,
      title,
      componentName: compName,
      componentPath,
      contentDir,
      intent,
      specPath: `${contentDir}/SPEC.md`,
      designPath: `${contentDir}/DESIGN.md`,
      passedPath: `${contentDir}/PASSED`,
      sectionTaskId,
      prevLastId: prevLastId || '',
      kebabName: toKebabCase(compName),
    };

    // ── Level 1: Section parent task ────────────────────────────────────
    await ctx.spawn({
      id: sectionTaskId,
      title: `Section: ${title}`,
      dependencies: prevLastId ? [prevLastId] : [],
      tags: ['section', `section-${sectionId}`],
      vars: {
        sectionId,
        sectionTitle: title,
        componentName: compName,
      },
      inputs: [
        'apps/landing/.content/sections.json',
        'apps/landing/.content/brand.json',
        'apps/landing/src/styles/tokens.json',
      ],
      outputs: [componentPath],
      body:
        `Parent task for the "${title}" section.\n\n` +
        `Pipeline: spec → design → build → integrate → verify.\n\n` +
        `Intent: ${intent || '(see SPEC.md)'}\n` +
        `Component: \`${componentPath}\`.\n`,
    });

    // ── Level 2: 5 step children, templated ────────────────────────────
    const steps = ['01-spec', '02-design', '03-build', '04-integrate', '05-verify'];
    for (const step of steps) {
      const id = `${prefix}-${step}`;
      const templatePath = `${TEMPLATE_ROOT}/section/tasks/{{prefix}}-${step}/TASK.md`;
      await ctx.spawn(
        { _type: 'template-ref', path: templatePath, vars },
        { id },
      );
    }

    prevLastId = `${prefix}-05-verify`;
  }
}
