/**
 * CLI handler for `converge tbench`.
 *
 * Creates a playbook-style run that:
 * 1. Loads terminal-bench tasks from a local directory
 * 2. Generates a Seed with one task per terminal-bench task
 * 3. Delegates to `converge run` for execution
 */

import { resolve, join } from "node:path";
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";

export interface TBenchCommandOptions {
  /** Project directory */
  dir?: string;
  /** Directory containing terminal-bench tasks */
  tasksDir: string;
  /** Filter to specific task ID(s), comma-separated */
  task?: string;
  /** Filter to specific category(ies), comma-separated */
  category?: string;
  /** Filter by difficulty level */
  difficulty?: string;
  /** Maximum number of tasks */
  limit?: number;
  /** Verbose output */
  verbose?: boolean;
}

/**
 * Handle the `converge tbench` command.
 * Writes a tbench playbook and task definition, then returns the
 * playbook name and filter for the caller to execute via `converge run`.
 */
export async function tbenchCommand(
  opts: TBenchCommandOptions,
): Promise<{ playbookName: string; epicId: string }> {
  const projectDir = resolve(opts.dir ?? process.cwd());
  const playbookName = "tbench";
  const playbookDir = join(projectDir, ".converge", "playbooks", playbookName);
  const tasksDir = join(playbookDir, "tasks", "001-tbench-run");

  const resolvedTasksDir = resolve(opts.tasksDir);

  // Build filter config for the Seed
  const filterConfig: Record<string, unknown> = {};
  if (opts.task) {
    filterConfig.taskIds = opts.task.split(",").map((s) => s.trim());
  }
  if (opts.category) {
    filterConfig.categories = opts.category.split(",").map((s) => s.trim());
  }
  if (opts.difficulty) {
    filterConfig.difficulty = opts.difficulty;
  }
  if (opts.limit !== undefined) {
    filterConfig.limit = opts.limit;
  }

  // Write playbook.yml
  if (!existsSync(playbookDir)) {
    await mkdir(playbookDir, { recursive: true });
  }

  await writeFile(
    join(playbookDir, "playbook.yml"),
    [
      "name: tbench",
      'description: "Terminal-bench evaluation run"',
      "",
      "run:",
      "  mode: autonomous",
      "  maxIterations: 500",
      "  maxTaskAttempts: 1",
      "  resume: true",
    ].join("\n"),
    "utf-8",
  );

  // Write TASK.md for the tbench root task
  if (!existsSync(tasksDir)) {
    await mkdir(tasksDir, { recursive: true });
  }

  const filterYaml =
    Object.keys(filterConfig).length > 0
      ? `\nvars:\n  filter: ${JSON.stringify(filterConfig)}`
      : "";

  await writeFile(
    join(tasksDir, "TASK.md"),
    `---
title: "Terminal-Bench Evaluation"
seed:
  type: nodejs
  path: tbench-seedData.ts
outputs:
  - .converge/journal/tbench/tasks/001-tbench-run/tasks/*${filterYaml}
---

# Terminal-Bench Evaluation

Run AI agent against terminal-bench tasks.
Each task is a real-world terminal challenge (sysadmin, code compilation, ML training, data processing) run in a sandboxed Docker container.
`,
    "utf-8",
  );

  // Write the Seed script
  await writeFile(
    join(tasksDir, "tbench-seedData.ts"),
    `/**
 * Seed script for terminal-bench — spawns one task per terminal-bench task.
 * Auto-generated by \`converge tbench\`.
 */
import { taskSpawner } from "@openplaybooks/converge-tbench";

const tasksDir = ${JSON.stringify(resolvedTasksDir)};
const filter = ${JSON.stringify(filterConfig, null, 2)};
export default taskSpawner(tasksDir, Object.keys(filter).length > 0 ? filter : undefined);
`,
    "utf-8",
  );

  if (opts.verbose) {
    console.log(`   Playbook written: ${playbookDir}`);
    console.log(`   Tasks dir: ${resolvedTasksDir}`);
    console.log(`   Filter: ${JSON.stringify(filterConfig)}`);
  }

  return { playbookName, epicId: "001-tbench-run" };
}
