// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 41 building entries from assets/quaternius/modular_dungeon_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-dungeon-mod-barrel", asset: "/assets/quaternius/modular_dungeon_pack/barrel.glb", name: "Quat Dungeon Mod: Barrel" },
  { slug: "quat-dungeon-mod-bars", asset: "/assets/quaternius/modular_dungeon_pack/bars.glb", name: "Quat Dungeon Mod: Bars" },
  { slug: "quat-dungeon-mod-bones", asset: "/assets/quaternius/modular_dungeon_pack/bones.glb", name: "Quat Dungeon Mod: Bones" },
  { slug: "quat-dungeon-mod-bones2", asset: "/assets/quaternius/modular_dungeon_pack/bones2.glb", name: "Quat Dungeon Mod: Bones2" },
  { slug: "quat-dungeon-mod-book2", asset: "/assets/quaternius/modular_dungeon_pack/book2.glb", name: "Quat Dungeon Mod: Book2" },
  { slug: "quat-dungeon-mod-book3", asset: "/assets/quaternius/modular_dungeon_pack/book3.glb", name: "Quat Dungeon Mod: Book3" },
  { slug: "quat-dungeon-mod-book_open", asset: "/assets/quaternius/modular_dungeon_pack/book_open.glb", name: "Quat Dungeon Mod: Book Open" },
  { slug: "quat-dungeon-mod-candelabrum", asset: "/assets/quaternius/modular_dungeon_pack/candelabrum.glb", name: "Quat Dungeon Mod: Candelabrum" },
  { slug: "quat-dungeon-mod-candelabrum_tall", asset: "/assets/quaternius/modular_dungeon_pack/candelabrum_tall.glb", name: "Quat Dungeon Mod: Candelabrum Tall" },
  { slug: "quat-dungeon-mod-candle", asset: "/assets/quaternius/modular_dungeon_pack/candle.glb", name: "Quat Dungeon Mod: Candle" },
  { slug: "quat-dungeon-mod-carpet", asset: "/assets/quaternius/modular_dungeon_pack/carpet.glb", name: "Quat Dungeon Mod: Carpet" },
  { slug: "quat-dungeon-mod-chest", asset: "/assets/quaternius/modular_dungeon_pack/chest.glb", name: "Quat Dungeon Mod: Chest" },
  { slug: "quat-dungeon-mod-chest_gold", asset: "/assets/quaternius/modular_dungeon_pack/chest_gold.glb", name: "Quat Dungeon Mod: Chest Gold" },
  { slug: "quat-dungeon-mod-column", asset: "/assets/quaternius/modular_dungeon_pack/column.glb", name: "Quat Dungeon Mod: Column" },
  { slug: "quat-dungeon-mod-column_broken", asset: "/assets/quaternius/modular_dungeon_pack/column_broken.glb", name: "Quat Dungeon Mod: Column Broken" },
  { slug: "quat-dungeon-mod-column_broken2", asset: "/assets/quaternius/modular_dungeon_pack/column_broken2.glb", name: "Quat Dungeon Mod: Column Broken2" },
  { slug: "quat-dungeon-mod-entrance", asset: "/assets/quaternius/modular_dungeon_pack/entrance.glb", name: "Quat Dungeon Mod: Entrance" },
  { slug: "quat-dungeon-mod-entrance2", asset: "/assets/quaternius/modular_dungeon_pack/entrance2.glb", name: "Quat Dungeon Mod: Entrance2" },
  { slug: "quat-dungeon-mod-modularcolumn_bottom", asset: "/assets/quaternius/modular_dungeon_pack/modularcolumn_bottom.glb", name: "Quat Dungeon Mod: Modularcolumn Bottom" },
  { slug: "quat-dungeon-mod-modularcolumn_middle", asset: "/assets/quaternius/modular_dungeon_pack/modularcolumn_middle.glb", name: "Quat Dungeon Mod: Modularcolumn Middle" },
  { slug: "quat-dungeon-mod-modularcolumn_top", asset: "/assets/quaternius/modular_dungeon_pack/modularcolumn_top.glb", name: "Quat Dungeon Mod: Modularcolumn Top" },
  { slug: "quat-dungeon-mod-modularfloor", asset: "/assets/quaternius/modular_dungeon_pack/modularfloor.glb", name: "Quat Dungeon Mod: Modularfloor" },
  { slug: "quat-dungeon-mod-modularstonewall", asset: "/assets/quaternius/modular_dungeon_pack/modularstonewall.glb", name: "Quat Dungeon Mod: Modularstonewall" },
  { slug: "quat-dungeon-mod-modularstonewall_entrancetop", asset: "/assets/quaternius/modular_dungeon_pack/modularstonewall_entrancetop.glb", name: "Quat Dungeon Mod: Modularstonewall Entrancetop" },
  { slug: "quat-dungeon-mod-modularstonewall_top", asset: "/assets/quaternius/modular_dungeon_pack/modularstonewall_top.glb", name: "Quat Dungeon Mod: Modularstonewall Top" },
  { slug: "quat-dungeon-mod-potion", asset: "/assets/quaternius/modular_dungeon_pack/potion.glb", name: "Quat Dungeon Mod: Potion" },
  { slug: "quat-dungeon-mod-potion2", asset: "/assets/quaternius/modular_dungeon_pack/potion2.glb", name: "Quat Dungeon Mod: Potion2" },
  { slug: "quat-dungeon-mod-potion3", asset: "/assets/quaternius/modular_dungeon_pack/potion3.glb", name: "Quat Dungeon Mod: Potion3" },
  { slug: "quat-dungeon-mod-potion4", asset: "/assets/quaternius/modular_dungeon_pack/potion4.glb", name: "Quat Dungeon Mod: Potion4" },
  { slug: "quat-dungeon-mod-potion5", asset: "/assets/quaternius/modular_dungeon_pack/potion5.glb", name: "Quat Dungeon Mod: Potion5" },
  { slug: "quat-dungeon-mod-potion6", asset: "/assets/quaternius/modular_dungeon_pack/potion6.glb", name: "Quat Dungeon Mod: Potion6" },
  { slug: "quat-dungeon-mod-rock1", asset: "/assets/quaternius/modular_dungeon_pack/rock1.glb", name: "Quat Dungeon Mod: Rock1" },
  { slug: "quat-dungeon-mod-rock2", asset: "/assets/quaternius/modular_dungeon_pack/rock2.glb", name: "Quat Dungeon Mod: Rock2" },
  { slug: "quat-dungeon-mod-rock3", asset: "/assets/quaternius/modular_dungeon_pack/rock3.glb", name: "Quat Dungeon Mod: Rock3" },
  { slug: "quat-dungeon-mod-rock4", asset: "/assets/quaternius/modular_dungeon_pack/rock4.glb", name: "Quat Dungeon Mod: Rock4" },
  { slug: "quat-dungeon-mod-rock5", asset: "/assets/quaternius/modular_dungeon_pack/rock5.glb", name: "Quat Dungeon Mod: Rock5" },
  { slug: "quat-dungeon-mod-stairs", asset: "/assets/quaternius/modular_dungeon_pack/stairs.glb", name: "Quat Dungeon Mod: Stairs" },
  { slug: "quat-dungeon-mod-torch", asset: "/assets/quaternius/modular_dungeon_pack/torch.glb", name: "Quat Dungeon Mod: Torch" },
  { slug: "quat-dungeon-mod-torch_wall", asset: "/assets/quaternius/modular_dungeon_pack/torch_wall.glb", name: "Quat Dungeon Mod: Torch Wall" },
  { slug: "quat-dungeon-mod-wallrocks", asset: "/assets/quaternius/modular_dungeon_pack/wallrocks.glb", name: "Quat Dungeon Mod: Wallrocks" },
  { slug: "quat-dungeon-mod-window", asset: "/assets/quaternius/modular_dungeon_pack/window.glb", name: "Quat Dungeon Mod: Window" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "building", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
