// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 30 building entries from assets/quaternius/modular_medieval_buildings_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-medieval-banner", asset: "/assets/quaternius/modular_medieval_buildings_pack/banner.glb", name: "Quat Medieval: Banner" },
  { slug: "quat-medieval-bridge", asset: "/assets/quaternius/modular_medieval_buildings_pack/bridge.glb", name: "Quat Medieval: Bridge" },
  { slug: "quat-medieval-door", asset: "/assets/quaternius/modular_medieval_buildings_pack/door.glb", name: "Quat Medieval: Door" },
  { slug: "quat-medieval-dummy", asset: "/assets/quaternius/modular_medieval_buildings_pack/dummy.glb", name: "Quat Medieval: Dummy" },
  { slug: "quat-medieval-largesimpletower", asset: "/assets/quaternius/modular_medieval_buildings_pack/largesimpletower.glb", name: "Quat Medieval: Largesimpletower" },
  { slug: "quat-medieval-largesquaretower", asset: "/assets/quaternius/modular_medieval_buildings_pack/largesquaretower.glb", name: "Quat Medieval: Largesquaretower" },
  { slug: "quat-medieval-largesquaretowerbricks", asset: "/assets/quaternius/modular_medieval_buildings_pack/largesquaretowerbricks.glb", name: "Quat Medieval: Largesquaretowerbricks" },
  { slug: "quat-medieval-largetower", asset: "/assets/quaternius/modular_medieval_buildings_pack/largetower.glb", name: "Quat Medieval: Largetower" },
  { slug: "quat-medieval-pointytower", asset: "/assets/quaternius/modular_medieval_buildings_pack/pointytower.glb", name: "Quat Medieval: Pointytower" },
  { slug: "quat-medieval-simpletower", asset: "/assets/quaternius/modular_medieval_buildings_pack/simpletower.glb", name: "Quat Medieval: Simpletower" },
  { slug: "quat-medieval-simpletowerbricks", asset: "/assets/quaternius/modular_medieval_buildings_pack/simpletowerbricks.glb", name: "Quat Medieval: Simpletowerbricks" },
  { slug: "quat-medieval-smallsquaretower", asset: "/assets/quaternius/modular_medieval_buildings_pack/smallsquaretower.glb", name: "Quat Medieval: Smallsquaretower" },
  { slug: "quat-medieval-smallsquaretowerbricks", asset: "/assets/quaternius/modular_medieval_buildings_pack/smallsquaretowerbricks.glb", name: "Quat Medieval: Smallsquaretowerbricks" },
  { slug: "quat-medieval-smalltower", asset: "/assets/quaternius/modular_medieval_buildings_pack/smalltower.glb", name: "Quat Medieval: Smalltower" },
  { slug: "quat-medieval-tallwall", asset: "/assets/quaternius/modular_medieval_buildings_pack/tallwall.glb", name: "Quat Medieval: Tallwall" },
  { slug: "quat-medieval-tallwallbricks", asset: "/assets/quaternius/modular_medieval_buildings_pack/tallwallbricks.glb", name: "Quat Medieval: Tallwallbricks" },
  { slug: "quat-medieval-tallwallentrance", asset: "/assets/quaternius/modular_medieval_buildings_pack/tallwallentrance.glb", name: "Quat Medieval: Tallwallentrance" },
  { slug: "quat-medieval-target", asset: "/assets/quaternius/modular_medieval_buildings_pack/target.glb", name: "Quat Medieval: Target" },
  { slug: "quat-medieval-targetwitharrows", asset: "/assets/quaternius/modular_medieval_buildings_pack/targetwitharrows.glb", name: "Quat Medieval: Targetwitharrows" },
  { slug: "quat-medieval-tower", asset: "/assets/quaternius/modular_medieval_buildings_pack/tower.glb", name: "Quat Medieval: Tower" },
  { slug: "quat-medieval-tunnel", asset: "/assets/quaternius/modular_medieval_buildings_pack/tunnel.glb", name: "Quat Medieval: Tunnel" },
  { slug: "quat-medieval-wall", asset: "/assets/quaternius/modular_medieval_buildings_pack/wall.glb", name: "Quat Medieval: Wall" },
  { slug: "quat-medieval-wallbricks", asset: "/assets/quaternius/modular_medieval_buildings_pack/wallbricks.glb", name: "Quat Medieval: Wallbricks" },
  { slug: "quat-medieval-wallentrance", asset: "/assets/quaternius/modular_medieval_buildings_pack/wallentrance.glb", name: "Quat Medieval: Wallentrance" },
  { slug: "quat-medieval-wallentrancebricks", asset: "/assets/quaternius/modular_medieval_buildings_pack/wallentrancebricks.glb", name: "Quat Medieval: Wallentrancebricks" },
  { slug: "quat-medieval-watchtower", asset: "/assets/quaternius/modular_medieval_buildings_pack/watchtower.glb", name: "Quat Medieval: Watchtower" },
  { slug: "quat-medieval-watchtowerwroof", asset: "/assets/quaternius/modular_medieval_buildings_pack/watchtowerwroof.glb", name: "Quat Medieval: Watchtowerwroof" },
  { slug: "quat-medieval-well", asset: "/assets/quaternius/modular_medieval_buildings_pack/well.glb", name: "Quat Medieval: Well" },
  { slug: "quat-medieval-windowgothic", asset: "/assets/quaternius/modular_medieval_buildings_pack/windowgothic.glb", name: "Quat Medieval: Windowgothic" },
  { slug: "quat-medieval-windowsquare", asset: "/assets/quaternius/modular_medieval_buildings_pack/windowsquare.glb", name: "Quat Medieval: Windowsquare" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "building", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
