#!/usr/bin/env node
/**
 * Emit assets/environment/scene-shell.js — a tilemap-style ground plus skybox,
 * lighting, and fog. All values derived from the palette in pitch.md.
 *
 * Tilemap shape: an N×N grid of square tiles, each at a slightly displaced
 * height (Perlin-ish noise from sin/cos) so the arena reads as low-poly hills.
 * Walkable centre stays flat-ish, edges drop off to suggest a bowl-shaped arena.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';

const TILES_PER_SIDE = 8;
const TILE_SIZE = 3;                       // world units per tile (so arena is 24×24)
const ARENA_HALF = (TILES_PER_SIDE * TILE_SIZE) / 2;

let palette = '';
try {
  const pitch = readFileSync('assets/pitch.md', 'utf-8');
  palette = pitch.match(/\*\*Palette\*\*:\s*(.+)/)?.[1] || '';
} catch {}

// Pull hex codes from the palette description. Slot them into roles based on
// position keywords near each hex — fall back to sensible defaults so a palette
// with only one hex (e.g. just an amber accent) doesn't accidentally repaint
// the whole arena that color.
const DEFAULT = { bgTop: '0x0e2a2a', ground: '0x3a5a40', accent: '0xf0a050', highlight: '0xfaf3e0' };
function findHex(role) {
  // Look for "<role-keyword> ... #hex" OR "#hex ... <role-keyword>" within ~40 chars.
  const keywords = {
    bgTop:     /sky|background|deep[-\s]?teal|teal|top/i,
    ground:    /ground|moss|green|grass|earth|terrain/i,
    accent:    /accent|amber|warm|highlight/i,
    highlight: /bone|white|highlight|cream/i,
  };
  const k = keywords[role].source;
  const re1 = new RegExp(`(?:${k})[^\\n]{0,40}#([0-9a-f]{6})`, 'i');
  const re2 = new RegExp(`#([0-9a-f]{6})[^\\n]{0,40}(?:${k})`, 'i');
  const m = palette.match(re1) || palette.match(re2);
  return m ? '0x' + m[1].toLowerCase() : DEFAULT[role];
}
const bgTop     = findHex('bgTop');
const ground    = findHex('ground');
const accent    = findHex('accent');
const highlight = findHex('highlight');

const moduleSrc = `// Generated by build_environment.js — do not edit by hand.
// Tilemap-style scene shell: ${TILES_PER_SIDE}×${TILES_PER_SIDE} tile grid, skybox, lighting, fog.

export function buildEnvironment(scene, THREE) {
  const TILES = ${TILES_PER_SIDE};
  const TILE = ${TILE_SIZE};
  const HALF = ${ARENA_HALF};

  // ── Tilemap ground ──
  // Each tile is an individual mesh so we can shade them slightly differently
  // for visual variety (low-poly tilemap aesthetic, not a continuous plane).
  const groundGroup = new THREE.Group();
  groundGroup.name = 'tilemap';

  // Shared geometries (cheaper than one per tile).
  const tileGeom = new THREE.BoxGeometry(TILE, 0.4, TILE);

  // Two-tone tile materials — the player sees a checker-ish pattern.
  const matA = new THREE.MeshStandardMaterial({ color: ${ground}, roughness: 0.95, flatShading: true });
  const matB = new THREE.MeshStandardMaterial({
    color: new THREE.Color(${ground}).lerp(new THREE.Color(${highlight}), 0.06),
    roughness: 0.95, flatShading: true,
  });

  for (let ix = 0; ix < TILES; ix++) {
    for (let iz = 0; iz < TILES; iz++) {
      const x = (ix - TILES / 2 + 0.5) * TILE;
      const z = (iz - TILES / 2 + 0.5) * TILE;
      // Edge tiles drop slightly so the arena has soft rim hills.
      const r2 = (x * x + z * z) / (HALF * HALF);
      const dy = Math.max(0, r2 - 0.5) * -0.8 + Math.sin(ix * 0.7) * Math.cos(iz * 0.7) * 0.08;
      const tile = new THREE.Mesh(tileGeom, (ix + iz) % 2 === 0 ? matA : matB);
      tile.position.set(x, dy - 0.2, z);
      tile.receiveShadow = true;
      groundGroup.add(tile);
    }
  }
  scene.add(groundGroup);

  // ── Skybox ──
  const skyGeom = new THREE.SphereGeometry(80, 24, 16);
  const skyColors = new Float32Array(skyGeom.attributes.position.count * 3);
  const top = new THREE.Color(${bgTop});
  const horizon = new THREE.Color(${accent});
  for (let i = 0; i < skyGeom.attributes.position.count; i++) {
    const y = skyGeom.attributes.position.getY(i);
    const t = Math.max(0, Math.min(1, (y + 80) / 160));
    const c = horizon.clone().lerp(top, t * t);
    skyColors[i * 3 + 0] = c.r; skyColors[i * 3 + 1] = c.g; skyColors[i * 3 + 2] = c.b;
  }
  skyGeom.setAttribute('color', new THREE.BufferAttribute(skyColors, 3));
  const sky = new THREE.Mesh(
    skyGeom,
    new THREE.MeshBasicMaterial({ vertexColors: true, side: THREE.BackSide, fog: false }),
  );
  scene.add(sky);

  // ── Lighting ──
  scene.add(new THREE.AmbientLight(${highlight}, 0.45));
  const sun = new THREE.DirectionalLight(${accent}, 1.1);
  sun.position.set(8, 14, 6);
  sun.castShadow = true;
  sun.shadow.mapSize.set(2048, 2048);
  sun.shadow.camera.left = -HALF; sun.shadow.camera.right = HALF;
  sun.shadow.camera.top = HALF; sun.shadow.camera.bottom = -HALF;
  sun.shadow.camera.near = 1; sun.shadow.camera.far = 50;
  scene.add(sun);

  // ── Fog ──
  scene.fog = new THREE.Fog(${bgTop}, HALF * 1.2, HALF * 3);

  return { arenaSize: HALF * 2, tilesPerSide: TILES };
}
`;

mkdirSync('assets/environment', { recursive: true });
writeFileSync('assets/environment/scene-shell.js', moduleSrc);
console.log(`✓ assets/environment/scene-shell.js (${TILES_PER_SIDE}×${TILES_PER_SIDE} tile grid, palette: bgTop=${bgTop}, ground=${ground}, accent=${accent})`);
