/**
 * WBS: Per-Screen Vertical Pipeline (2-level)
 *
 * Level 1: One parent task per screen
 * Level 2: 6 sequential step tasks per screen
 *   1. Spec → 2. Design → 3. Convert → 4. Analyze → 5. Split → 6. Lift
 *
 * Screens run sequentially — each screen's last step blocks the next screen's first step.
 *
 * Task content comes from wbs/templates/screen/ — a folder of TASK.md files with
 * {{var}} placeholders substituted at render time by the framework.
 * Each screen's `htmlReference` from `.stitch/screens.json` is passed as `htmlReference`
 * and `htmlReferenceInput` (optional YAML inputs line when non-empty).
 */

import { readFileSync, readdirSync, existsSync, statSync } from 'fs';
import { join } from 'path';

import { toPascalCase, toSnakeCase, routeToScreenPath, routeToWidgetsDir } from './helpers.js';

/**
 * When .stitch/screens.json is missing, derive screens from .stitch/designs/v1/ folders.
 * Each subfolder with a code.html is treated as a screen, using the folder name as the id
 * and a kebab-cased route derived from it.
 */
function deriveScreensFromDesigns(projectDir) {
  const designsDir = join(projectDir, '.stitch/designs/v1');
  if (!existsSync(designsDir)) return [];

  const entries = readdirSync(designsDir).filter(name => {
    const full = join(designsDir, name);
    return statSync(full).isDirectory() && existsSync(join(full, 'code.html'));
  });

  return entries.map(folder => ({
    id: folder,
    title: folder.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
    route: '/' + folder.replace(/_/g, '-'),
  }));
}

export async function run(ctx) {
  const screensPath = join(ctx.projectDir, '.stitch/screens.json');
  let screens;

  if (existsSync(screensPath)) {
    const raw = JSON.parse(readFileSync(screensPath, 'utf-8'));
    screens = (Array.isArray(raw) ? raw : raw.screens ?? [])
      .filter(s => s.route && s.route.startsWith('/'));
  } else {
    ctx.log.warn(
      `.stitch/screens.json not found — deriving screens from .stitch/designs/v1/ folders.`
    );
    screens = deriveScreensFromDesigns(ctx.projectDir);
  }

  if (!screens || screens.length === 0) {
    throw new Error(
      `No screens found. Ensure .stitch/screens.json exists (generated by task ` +
      `'004-breakdown-ux-to-screens') or .stitch/designs/v1/ contains screen folders.`
    );
  }

  const templateBase = '.converge/playbooks/default/tasks/03-build-screens/wbs/templates/screen';
  let prevScreenLastId = null;

  for (let idx = 0; idx < screens.length; idx++) {
    const screen = screens[idx];
    const { id: screenId, title, route } = screen;
    const htmlReference =
      typeof screen.htmlReference === 'string' ? screen.htmlReference.trim() : '';
    const htmlReferenceInput = htmlReference
      ? `  - "${htmlReference.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"\n`
      : '';
    const prefix = String(idx + 1).padStart(3, '0');
    const widgetName = toPascalCase(screenId);
    const snakeName = toSnakeCase(screenId);
    const screenPath = routeToScreenPath(route, screenId);
    const widgetsJsonPath = `.stitch/designs/${screenId}/widgets.jsonl`;
    const localWidgetsDir = routeToWidgetsDir(screenId);
    const screenTaskId = `${prefix}-${screenId}`;

    const vars = {
      prefix, screenId, title, widgetName, snakeName, route,
      screenPath, widgetsJsonPath, localWidgetsDir, screenTaskId,
      specPath: `.stitch/designs/${screenId}/SPEC.md`,
      metaPath: `.stitch/designs/${screenId}/META.md`,
      designPath: `.stitch/designs/${screenId}/design.html`,
      prevScreenLastId: prevScreenLastId || '',
      htmlReference,
      htmlReferenceInput,
    };

    // ── Level 1: Screen parent task ──────────────────────────────
    await ctx.spawn({
      id: screenTaskId,
      title: `Screen: ${title}`,
      dependencies: prevScreenLastId ? [prevScreenLastId] : [],
      tags: ['screen', `screen-${screenId}`],
      vars: { screenId, screenTitle: title, widgetName, route, htmlReference },
      inputs: [
        '.stitch/screens.json',
        '.stitch/system/DESIGN.md',
        '.stitch/UX.md',
        '.stitch/DESIGN.md',
        '.stitch/designs/v1/DESIGN.md',
      ],
      outputs: [screenPath],
      body: `Parent task for building the "${title}" screen through the full pipeline: spec → design → convert → analyze → split → lift.`,
    });

    // ── Level 2: Step children (from templates) ──────────────────
    const steps = ['01-spec', '02-design', '03-convert', '04-analyze', '05-split', '06-lift'];

    for (const step of steps) {
      const id = `${prefix}-${step}`;
      const templatePath = `${templateBase}/tasks/{{prefix}}-${step}/TASK.md`;

      await ctx.spawn(
        { _type: 'template-ref', path: templatePath, vars },
        { id }
      );
    }

    prevScreenLastId = `${prefix}-06-lift`;
  }
}
