/**
 * WBS: Per-Screen Vertical Pipeline (2-level)
 *
 * Level 1: One parent task per screen
 * Level 2: 6 sequential step tasks per screen
 *   1. Spec → 2. Design → 3. Convert → 4. Analyze → 5. Split → 6. Lift
 *
 * Screens run sequentially — each screen's last step blocks the next screen's first step.
 *
 * Task content comes from wbs/templates/screen/ — a folder of TASK.md files with
 * {{var}} placeholders substituted at render time by the framework.
 * Each screen's `htmlReference` from `.stitch/screens.json` is passed as `htmlReference`
 * and `htmlReferenceInput` (optional YAML inputs line when non-empty).
 */

import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

import { toPascalCase, toSnakeCase, routeToScreenPath, routeToWidgetsDir } from './helpers.js';

export async function run(ctx) {
  const screensPath = join(ctx.projectDir, '.stitch/screens.json');

  if (!existsSync(screensPath)) {
    throw new Error(
      `Missing required file: .stitch/screens.json\n` +
      `This file should be generated by task '004-breakdown-ux-to-screens' in epic 01-prepare-requirements.`
    );
  }

  const raw = JSON.parse(readFileSync(screensPath, 'utf-8'));
  const screens = (Array.isArray(raw) ? raw : raw.screens)
    .filter(s => s.route.startsWith('/'));

  if (!screens || screens.length === 0) {
    throw new Error('screens.json has no screens defined');
  }

  const templateBase = '.converge/playbooks/default/tasks/03-build-screens/wbs/templates/screen';
  let prevScreenLastId = null;

  for (let idx = 0; idx < screens.length; idx++) {
    const screen = screens[idx];
    const { id: screenId, title, route } = screen;
    const htmlReference =
      typeof screen.htmlReference === 'string' ? screen.htmlReference.trim() : '';
    const htmlReferenceInput = htmlReference
      ? `  - "${htmlReference.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"\n`
      : '';
    const prefix = String(idx + 1).padStart(3, '0');
    const widgetName = toPascalCase(screenId);
    const snakeName = toSnakeCase(screenId);
    const screenPath = routeToScreenPath(route, screenId);
    const widgetsJsonPath = `.stitch/designs/${screenId}/widgets.jsonl`;
    const localWidgetsDir = routeToWidgetsDir(screenId);
    const screenTaskId = `${prefix}-${screenId}`;

    const vars = {
      prefix, screenId, title, widgetName, snakeName, route,
      screenPath, widgetsJsonPath, localWidgetsDir, screenTaskId,
      specPath: `.stitch/designs/${screenId}/SPEC.md`,
      metaPath: `.stitch/designs/${screenId}/META.md`,
      designPath: `.stitch/designs/${screenId}/design.html`,
      prevScreenLastId: prevScreenLastId || '',
      htmlReference,
      htmlReferenceInput,
    };

    // ── Level 1: Screen parent task ──────────────────────────────
    await ctx.spawn({
      id: screenTaskId,
      title: `Screen: ${title}`,
      dependencies: prevScreenLastId ? [prevScreenLastId] : [],
      tags: ['screen', `screen-${screenId}`],
      vars: { screenId, screenTitle: title, widgetName, route, htmlReference },
      inputs: ['.stitch/screens.json', '.stitch/system/DESIGN.md', '.stitch/UX.md'],
      outputs: [screenPath],
      body: `Parent task for building the "${title}" screen through the full pipeline: spec → design → convert → analyze → split → lift.`,
    });

    // ── Level 2: Step children (from templates) ──────────────────
    const basePath = `.converge/playbooks/default/tasks/03-build-screens/tasks/${screenTaskId}`;
    const steps = ['01-spec', '02-design', '03-convert', '04-analyze', '05-split', '06-lift'];

    for (const step of steps) {
      const id = `${prefix}-${step}`;
      const templatePath = `${templateBase}/tasks/{{prefix}}-${step}/TASK.md`;
      const writeToPath = `${basePath}/tasks/${id}/TASK.md`;

      await ctx.spawn(
        { _type: 'template-ref', path: templatePath, vars },
        { id, writeToPath }
      );
    }

    prevScreenLastId = `${prefix}-06-lift`;
  }
}
