// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 22 prop entries from assets/kenney/mini-arena.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "mini-arena-banner", asset: "/assets/kenney/mini-arena/banner.glb", name: "Mini Arena: Banner" },
  { slug: "mini-arena-block", asset: "/assets/kenney/mini-arena/block.glb", name: "Mini Arena: Block" },
  { slug: "mini-arena-border-corner", asset: "/assets/kenney/mini-arena/border-corner.glb", name: "Mini Arena: Corner" },
  { slug: "mini-arena-border-straight", asset: "/assets/kenney/mini-arena/border-straight.glb", name: "Mini Arena: Straight" },
  { slug: "mini-arena-bricks", asset: "/assets/kenney/mini-arena/bricks.glb", name: "Mini Arena: Bricks" },
  { slug: "mini-arena-character-soldier", asset: "/assets/kenney/mini-arena/character-soldier.glb", name: "Mini Arena: Soldier" },
  { slug: "mini-arena-column-damaged", asset: "/assets/kenney/mini-arena/column-damaged.glb", name: "Mini Arena: Damaged" },
  { slug: "mini-arena-column", asset: "/assets/kenney/mini-arena/column.glb", name: "Mini Arena: Column" },
  { slug: "mini-arena-floor-detail", asset: "/assets/kenney/mini-arena/floor-detail.glb", name: "Mini Arena: Detail" },
  { slug: "mini-arena-floor", asset: "/assets/kenney/mini-arena/floor.glb", name: "Mini Arena: Floor" },
  { slug: "mini-arena-stairs-corner-inner", asset: "/assets/kenney/mini-arena/stairs-corner-inner.glb", name: "Mini Arena: Corner-Inner" },
  { slug: "mini-arena-stairs-corner", asset: "/assets/kenney/mini-arena/stairs-corner.glb", name: "Mini Arena: Corner" },
  { slug: "mini-arena-stairs", asset: "/assets/kenney/mini-arena/stairs.glb", name: "Mini Arena: Stairs" },
  { slug: "mini-arena-statue", asset: "/assets/kenney/mini-arena/statue.glb", name: "Mini Arena: Statue" },
  { slug: "mini-arena-tree", asset: "/assets/kenney/mini-arena/tree.glb", name: "Mini Arena: Tree" },
  { slug: "mini-arena-trophy", asset: "/assets/kenney/mini-arena/trophy.glb", name: "Mini Arena: Trophy" },
  { slug: "mini-arena-wall-corner", asset: "/assets/kenney/mini-arena/wall-corner.glb", name: "Mini Arena: Corner" },
  { slug: "mini-arena-wall-gate", asset: "/assets/kenney/mini-arena/wall-gate.glb", name: "Mini Arena: Gate" },
  { slug: "mini-arena-wall", asset: "/assets/kenney/mini-arena/wall.glb", name: "Mini Arena: Wall" },
  { slug: "mini-arena-weapon-rack", asset: "/assets/kenney/mini-arena/weapon-rack.glb", name: "Mini Arena: Rack" },
  { slug: "mini-arena-weapon-spear", asset: "/assets/kenney/mini-arena/weapon-spear.glb", name: "Mini Arena: Spear" },
  { slug: "mini-arena-weapon-sword", asset: "/assets/kenney/mini-arena/weapon-sword.glb", name: "Mini Arena: Sword" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
