// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 11 character entries from assets/quaternius/modular_men.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-man-adventurer", asset: "/assets/quaternius/modular_men/adventurer.glb", name: "Quat Man: Adventurer" },
  { slug: "quat-man-beach", asset: "/assets/quaternius/modular_men/beach.glb", name: "Quat Man: Beach" },
  { slug: "quat-man-casual", asset: "/assets/quaternius/modular_men/casual.glb", name: "Quat Man: Casual" },
  { slug: "quat-man-casual2", asset: "/assets/quaternius/modular_men/casual2.glb", name: "Quat Man: Casual2" },
  { slug: "quat-man-farmer", asset: "/assets/quaternius/modular_men/farmer.glb", name: "Quat Man: Farmer" },
  { slug: "quat-man-king", asset: "/assets/quaternius/modular_men/king.glb", name: "Quat Man: King" },
  { slug: "quat-man-punk", asset: "/assets/quaternius/modular_men/punk.glb", name: "Quat Man: Punk" },
  { slug: "quat-man-spacesuit", asset: "/assets/quaternius/modular_men/spacesuit.glb", name: "Quat Man: Spacesuit" },
  { slug: "quat-man-suit", asset: "/assets/quaternius/modular_men/suit.glb", name: "Quat Man: Suit" },
  { slug: "quat-man-swat", asset: "/assets/quaternius/modular_men/swat.glb", name: "Quat Man: Swat" },
  { slug: "quat-man-worker", asset: "/assets/quaternius/modular_men/worker.glb", name: "Quat Man: Worker" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
