// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 10 character entries from assets/quaternius/modular_women.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-woman-adventurer", asset: "/assets/quaternius/modular_women/adventurer.glb", name: "Quat Woman: Adventurer" },
  { slug: "quat-woman-casual", asset: "/assets/quaternius/modular_women/casual.glb", name: "Quat Woman: Casual" },
  { slug: "quat-woman-formal", asset: "/assets/quaternius/modular_women/formal.glb", name: "Quat Woman: Formal" },
  { slug: "quat-woman-medieval", asset: "/assets/quaternius/modular_women/medieval.glb", name: "Quat Woman: Medieval" },
  { slug: "quat-woman-punk", asset: "/assets/quaternius/modular_women/punk.glb", name: "Quat Woman: Punk" },
  { slug: "quat-woman-scifi", asset: "/assets/quaternius/modular_women/scifi.glb", name: "Quat Woman: Scifi" },
  { slug: "quat-woman-soldier", asset: "/assets/quaternius/modular_women/soldier.glb", name: "Quat Woman: Soldier" },
  { slug: "quat-woman-suit", asset: "/assets/quaternius/modular_women/suit.glb", name: "Quat Woman: Suit" },
  { slug: "quat-woman-witch", asset: "/assets/quaternius/modular_women/witch.glb", name: "Quat Woman: Witch" },
  { slug: "quat-woman-worker", asset: "/assets/quaternius/modular_women/worker.glb", name: "Quat Woman: Worker" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
