import type {
  PlaybookSummary,
  PlaybookDetail,
  TaskNode,
  RunState,
  Gap,
  JournalEvent,
  StudioSession,
  SkillSummary,
  ProviderInfo,
} from './types';

export const MOCK_PLAYBOOKS: PlaybookSummary[] = [
  {
    name: 'data-pipeline',
    description: 'Extract, transform, and load data from legacy PostgreSQL into the new event-driven warehouse',
    status: 'complete',
    updatedAt: '2026-05-27T09:14:22.000Z',
    taskCount: 12,
  },
  {
    name: 'ci-cd-setup',
    description: 'Configure GitHub Actions workflows with build, test, lint, and deploy stages for the monorepo',
    status: 'running',
    updatedAt: '2026-05-27T10:02:47.000Z',
    taskCount: 8,
  },
  {
    name: 'api-migration',
    description: 'Migrate REST v2 endpoints to GraphQL with schema stitching, batched resolvers, and backward-compat shim',
    status: 'error',
    updatedAt: '2026-05-26T22:31:05.000Z',
    taskCount: 15,
  },
  {
    name: 'security-audit',
    description: 'Comprehensive dependency audit, SAST scan, secret rotation, and OWASP top-10 verification',
    status: 'pending',
    updatedAt: '2026-05-25T14:00:00.000Z',
    taskCount: 6,
  },
];

const dataPipelineTasks: TaskNode[] = [
  {
    id: 'extract-schema',
    title: 'Extract source schema from PostgreSQL',
    status: 'pass',
    mode: 'task',
    dependsOn: [],
    dependedOnBy: ['generate-mappings', 'validate-schema'],
    inputs: ['postgres://warehouse-legacy/public'],
    outputs: ['artifacts/schema.json'],
    checks: [
      { id: 'chk-schema-valid', label: 'Schema JSON is valid', passed: true },
      { id: 'chk-tables-present', label: 'All 47 source tables captured', passed: true },
    ],
    attempts: [
      { attempt: 1, status: 'pass', durationMs: 4230 },
    ],
    spawnedChildren: [],
    dagType: 'normal',
  },
  {
    id: 'validate-schema',
    title: 'Run schema compatibility checks',
    status: 'pass',
    mode: 'task',
    dependsOn: ['extract-schema'],
    dependedOnBy: ['generate-mappings'],
    inputs: ['artifacts/schema.json'],
    outputs: ['artifacts/schema-report.md'],
    checks: [
      { id: 'chk-no-breaking', label: 'No breaking column renames detected', passed: true },
    ],
    attempts: [
      { attempt: 1, status: 'error', durationMs: 1120, error: 'Timeout connecting to validation service' },
      { attempt: 2, status: 'pass', durationMs: 980 },
    ],
    spawnedChildren: [],
    dagType: 'normal',
  },
  {
    id: 'generate-mappings',
    title: 'Generate field-level transform mappings',
    status: 'pass',
    mode: 'spawner',
    dependsOn: ['extract-schema', 'validate-schema'],
    dependedOnBy: ['build-etl-image'],
    inputs: ['artifacts/schema.json', 'artifacts/schema-report.md'],
    outputs: ['artifacts/mappings/'],
    checks: [
      { id: 'chk-mapping-count', label: 'One mapping per source table', passed: true },
      { id: 'chk-type-coverage', label: 'All column types handled', passed: true },
    ],
    attempts: [
      { attempt: 1, status: 'pass', durationMs: 12400 },
    ],
    spawnedChildren: ['mapping-users', 'mapping-orders', 'mapping-events'],
    dagType: 'diverge',
  },
  {
    id: 'mapping-users',
    title: 'Transform mapping: users table',
    status: 'pass',
    mode: 'task',
    dependsOn: ['generate-mappings'],
    dependedOnBy: ['merge-mappings'],
    inputs: ['artifacts/schema.json'],
    outputs: ['artifacts/mappings/users.json'],
    checks: [],
    attempts: [
      { attempt: 1, status: 'pass', durationMs: 3100 },
    ],
    spawnedChildren: [],
    dagType: 'normal',
  },
  {
    id: 'mapping-orders',
    title: 'Transform mapping: orders table',
    status: 'running',
    mode: 'task',
    dependsOn: ['generate-mappings'],
    dependedOnBy: ['merge-mappings'],
    inputs: ['artifacts/schema.json'],
    outputs: ['artifacts/mappings/orders.json'],
    checks: [],
    attempts: [
      { attempt: 1, status: 'running', durationMs: 0 },
    ],
    spawnedChildren: [],
    dagType: 'normal',
  },
  {
    id: 'mapping-events',
    title: 'Transform mapping: events table',
    status: 'error',
    mode: 'task',
    dependsOn: ['generate-mappings'],
    dependedOnBy: ['merge-mappings'],
    inputs: ['artifacts/schema.json'],
    outputs: ['artifacts/mappings/events.json'],
    checks: [
      { id: 'chk-event-schema', label: 'Event payload conforms to Avro schema', passed: false, output: 'Field "metadata" is map<string> in source but jsonb in target' },
    ],
    attempts: [
      { attempt: 1, status: 'error', durationMs: 5800, error: 'Type mismatch: metadata column cannot be auto-coerced from jsonb to map<string>' },
      { attempt: 2, status: 'error', durationMs: 6200, error: 'Custom coercer threw: unsupported nested array in metadata.tags' },
    ],
    spawnedChildren: [],
    dagType: 'normal',
  },
  {
    id: 'merge-mappings',
    title: 'Converge all transform mappings into unified config',
    status: 'blocked',
    mode: 'converger',
    dependsOn: ['mapping-users', 'mapping-orders', 'mapping-events'],
    dependedOnBy: ['build-etl-image'],
    inputs: ['artifacts/mappings/'],
    outputs: ['artifacts/unified-transform.yaml'],
    checks: [],
    attempts: [],
    spawnedChildren: [],
    dagType: 'converge',
  },
  {
    id: 'build-etl-image',
    title: 'Build Docker image for ETL pipeline',
    status: 'pending',
    mode: 'task',
    dependsOn: ['merge-mappings'],
    dependedOnBy: ['deploy-staging', 'run-integration-tests'],
    inputs: ['artifacts/unified-transform.yaml', 'Dockerfile.etl'],
    outputs: ['registry.internal/etl-pipeline:latest'],
    checks: [
      { id: 'chk-image-size', label: 'Image under 500MB', passed: false, output: 'Not yet built' },
    ],
    attempts: [],
    spawnedChildren: [],
    dagType: 'normal',
  },
  {
    id: 'run-integration-tests',
    title: 'Run integration test suite against staging',
    status: 'pending',
    mode: 'gateway',
    dependsOn: ['build-etl-image'],
    dependedOnBy: ['deploy-production'],
    inputs: ['registry.internal/etl-pipeline:latest'],
    outputs: ['artifacts/test-results.xml'],
    checks: [],
    attempts: [],
    spawnedChildren: [],
    dagType: 'normal',
  },
  {
    id: 'deploy-staging',
    title: 'Deploy ETL pipeline to staging environment',
    status: 'pending',
    mode: 'task',
    dependsOn: ['build-etl-image'],
    dependedOnBy: ['run-integration-tests'],
    inputs: ['registry.internal/etl-pipeline:latest'],
    outputs: ['artifacts/deploy-staging.log'],
    checks: [],
    attempts: [],
    spawnedChildren: [],
    dagType: 'normal',
  },
  {
    id: 'deploy-production',
    title: 'Deploy ETL pipeline to production',
    status: 'pending',
    mode: 'gateway',
    dependsOn: ['run-integration-tests'],
    dependedOnBy: [],
    inputs: ['artifacts/test-results.xml'],
    outputs: ['artifacts/deploy-production.log'],
    checks: [],
    attempts: [],
    spawnedChildren: [],
    dagType: 'normal',
  },
];

export const MOCK_PLAYBOOK_DETAIL: Record<string, PlaybookDetail> = {
  'data-pipeline': {
    name: 'data-pipeline',
    description: 'Extract, transform, and load data from legacy PostgreSQL into the new event-driven warehouse',
    status: 'running',
    updatedAt: '2026-05-27T10:02:47.000Z',
    taskCount: 12,
    tasks: dataPipelineTasks,
    goals: [
      { id: 'goal-schema-extracted', description: 'All source table schemas extracted and validated', status: 'active', checks: ['chk-schema-valid', 'chk-tables-present'] },
      { id: 'goal-mappings-complete', description: 'Transform mappings cover every source table', status: 'active', checks: ['chk-mapping-count', 'chk-type-coverage'] },
      { id: 'goal-tests-green', description: 'Integration test suite passes with zero failures', status: 'candidate', checks: [] },
      { id: 'goal-prod-deploy', description: 'Production deployment succeeds and healthcheck is green', status: 'candidate', checks: [] },
    ],
    runConfig: {
      maxTaskAttempts: 3,
      workers: 4,
      maxDuration: '2h',
    },
  },
  'ci-cd-setup': {
    name: 'ci-cd-setup',
    description: 'Configure GitHub Actions workflows with build, test, lint, and deploy stages for the monorepo',
    status: 'running',
    updatedAt: '2026-05-27T10:02:47.000Z',
    taskCount: 8,
    tasks: [
      {
        id: 'scaffold-workflows',
        title: 'Scaffold GitHub Actions workflow directory',
        status: 'pass',
        mode: 'task',
        dependsOn: [],
        dependedOnBy: ['build-stage', 'lint-stage'],
        inputs: [],
        outputs: ['.github/workflows/'],
        checks: [{ id: 'chk-dir-exists', label: 'Workflows directory created', passed: true }],
        attempts: [{ attempt: 1, status: 'pass', durationMs: 1200 }],
        spawnedChildren: [],
        dagType: 'normal',
      },
      {
        id: 'build-stage',
        title: 'Configure build stage with caching',
        status: 'pass',
        mode: 'task',
        dependsOn: ['scaffold-workflows'],
        dependedOnBy: ['test-stage'],
        inputs: ['.github/workflows/'],
        outputs: ['.github/workflows/build.yml'],
        checks: [{ id: 'chk-build-yaml', label: 'Build workflow is valid YAML', passed: true }],
        attempts: [{ attempt: 1, status: 'pass', durationMs: 3400 }],
        spawnedChildren: [],
        dagType: 'normal',
      },
      {
        id: 'lint-stage',
        title: 'Configure ESLint and Prettier stages',
        status: 'running',
        mode: 'task',
        dependsOn: ['scaffold-workflows'],
        dependedOnBy: ['test-stage'],
        inputs: ['.github/workflows/'],
        outputs: ['.github/workflows/lint.yml'],
        checks: [],
        attempts: [{ attempt: 1, status: 'running', durationMs: 0 }],
        spawnedChildren: [],
        dagType: 'normal',
      },
      {
        id: 'test-stage',
        title: 'Configure test matrix with coverage',
        status: 'pending',
        mode: 'task',
        dependsOn: ['build-stage', 'lint-stage'],
        dependedOnBy: ['deploy-stage'],
        inputs: ['.github/workflows/build.yml', '.github/workflows/lint.yml'],
        outputs: ['.github/workflows/test.yml'],
        checks: [],
        attempts: [],
        spawnedChildren: [],
        dagType: 'normal',
      },
      {
        id: 'deploy-stage',
        title: 'Configure deployment stage for staging and production',
        status: 'pending',
        mode: 'gateway',
        dependsOn: ['test-stage'],
        dependedOnBy: [],
        inputs: ['.github/workflows/test.yml'],
        outputs: ['.github/workflows/deploy.yml'],
        checks: [],
        attempts: [],
        spawnedChildren: [],
        dagType: 'normal',
      },
    ],
    goals: [
      { id: 'goal-ci-green', description: 'Full CI pipeline runs green on sample PR', status: 'active', checks: [] },
    ],
    runConfig: {
      maxTaskAttempts: 2,
      workers: 2,
    },
  },
};

export const MOCK_RUN_STATE: RunState = {
  executionId: 'exec-dp-20260527-091422',
  playbook: 'data-pipeline',
  status: 'running',
  generatedAt: '2026-05-27T09:14:22.000Z',
  totalNodes: 11,
  nodes: dataPipelineTasks,
};

export const MOCK_GAPS: Gap[] = [
  {
    id: 'gap-001',
    type: 'output',
    level: 'task',
    scope: 'mapping-events',
    description: 'Missing output: artifacts/mappings/events.json was not produced after two attempts',
    detected: '2026-05-27T09:42:18.000Z',
    resolved: false,
    severity: 'critical',
  },
  {
    id: 'gap-002',
    type: 'check-failed',
    level: 'task',
    scope: 'mapping-events',
    description: 'Check failed: Event payload Avro schema validation — metadata field type mismatch (jsonb vs map<string>)',
    detected: '2026-05-27T09:43:01.000Z',
    resolved: false,
    severity: 'high',
  },
  {
    id: 'gap-003',
    type: 'blocker',
    level: 'task',
    scope: 'merge-mappings',
    description: 'Blocked: merge-mappings cannot proceed — upstream task mapping-events is in error state',
    detected: '2026-05-27T09:43:05.000Z',
    resolved: false,
    severity: 'high',
  },
  {
    id: 'gap-004',
    type: 'plan',
    level: 'project',
    scope: 'data-pipeline',
    description: 'No rollback strategy defined for production deployment — if the ETL job fails mid-load the target warehouse may have partial data',
    detected: '2026-05-27T08:55:00.000Z',
    resolved: false,
    severity: 'medium',
  },
  {
    id: 'gap-005',
    type: 'insufficient-evidence',
    level: 'task',
    scope: 'validate-schema',
    description: 'Schema compatibility report does not cover the 3 newly added partitioned tables (events_2026_q1, events_2026_q2, events_2026_q3)',
    detected: '2026-05-27T09:20:12.000Z',
    resolved: true,
    severity: 'low',
  },
];

export const MOCK_JOURNAL_EVENTS: JournalEvent[] = [
  {
    timestamp: '2026-05-27T09:14:22.000Z',
    eventType: 'SESSION_START',
    level: 'project',
    scope: 'data-pipeline',
    message: 'Execution session started for playbook data-pipeline',
    metadata: { executionId: 'exec-dp-20260527-091422', workers: 4 },
  },
  {
    timestamp: '2026-05-27T09:14:23.000Z',
    eventType: 'ITERATION_START',
    level: 'project',
    scope: 'data-pipeline',
    message: 'Iteration 1 — scheduling root tasks',
    metadata: { iteration: 1 },
  },
  {
    timestamp: '2026-05-27T09:14:24.000Z',
    eventType: 'TASK_START',
    level: 'task',
    scope: 'extract-schema',
    message: 'Starting task: Extract source schema from PostgreSQL',
    metadata: { attempt: 1, agent: 'claude' },
  },
  {
    timestamp: '2026-05-27T09:14:28.000Z',
    eventType: 'CHECK_PASSED',
    level: 'task',
    scope: 'extract-schema',
    message: 'Check passed: Schema JSON is valid',
    metadata: { checkId: 'chk-schema-valid' },
  },
  {
    timestamp: '2026-05-27T09:14:28.500Z',
    eventType: 'TASK_COMPLETE',
    level: 'task',
    scope: 'extract-schema',
    message: 'Task completed in 4230ms',
    metadata: { durationMs: 4230 },
  },
  {
    timestamp: '2026-05-27T09:14:29.000Z',
    eventType: 'TASK_START',
    level: 'task',
    scope: 'validate-schema',
    message: 'Starting task: Run schema compatibility checks',
    metadata: { attempt: 1, agent: 'claude' },
  },
  {
    timestamp: '2026-05-27T09:14:30.100Z',
    eventType: 'TASK_FAILED',
    level: 'task',
    scope: 'validate-schema',
    message: 'Task failed: Timeout connecting to validation service',
    metadata: { attempt: 1, error: 'Timeout connecting to validation service' },
  },
  {
    timestamp: '2026-05-27T09:14:30.200Z',
    eventType: 'CORRECTION_LOOP_START',
    level: 'task',
    scope: 'validate-schema',
    message: 'Starting correction loop for validate-schema (attempt 2)',
    metadata: { attempt: 2 },
  },
  {
    timestamp: '2026-05-27T09:14:30.400Z',
    eventType: 'CORRECTION_ATTEMPTED',
    level: 'task',
    scope: 'validate-schema',
    message: 'Retry with increased timeout (30s -> 60s)',
    metadata: { strategy: 'increase-timeout', previousTimeout: 30000, newTimeout: 60000 },
  },
  {
    timestamp: '2026-05-27T09:14:31.300Z',
    eventType: 'TASK_COMPLETE',
    level: 'task',
    scope: 'validate-schema',
    message: 'Task completed on retry (attempt 2) in 980ms',
    metadata: { attempt: 2, durationMs: 980 },
  },
  {
    timestamp: '2026-05-27T09:14:31.500Z',
    eventType: 'ITERATION_COMPLETE',
    level: 'project',
    scope: 'data-pipeline',
    message: 'Iteration 1 complete — 2 tasks finished, scheduling next wave',
    metadata: { iteration: 1, completed: 2, remaining: 9 },
  },
  {
    timestamp: '2026-05-27T09:14:32.000Z',
    eventType: 'ITERATION_START',
    level: 'project',
    scope: 'data-pipeline',
    message: 'Iteration 2 — scheduling generate-mappings',
    metadata: { iteration: 2 },
  },
  {
    timestamp: '2026-05-27T09:14:32.100Z',
    eventType: 'TASK_START',
    level: 'task',
    scope: 'generate-mappings',
    message: 'Starting spawner task: Generate field-level transform mappings',
    metadata: { attempt: 1, mode: 'spawner', agent: 'claude' },
  },
  {
    timestamp: '2026-05-27T09:14:44.500Z',
    eventType: 'TASK_COMPLETE',
    level: 'task',
    scope: 'generate-mappings',
    message: 'Spawner completed — created 3 child tasks',
    metadata: { durationMs: 12400, spawnedChildren: ['mapping-users', 'mapping-orders', 'mapping-events'] },
  },
  {
    timestamp: '2026-05-27T09:14:45.000Z',
    eventType: 'AGENT_START',
    level: 'task',
    scope: 'mapping-users',
    message: 'Agent claude assigned to mapping-users',
    metadata: { agent: 'claude', model: 'claude-sonnet-4-20250514' },
  },
  {
    timestamp: '2026-05-27T09:14:45.100Z',
    eventType: 'TASK_START',
    level: 'task',
    scope: 'mapping-users',
    message: 'Starting task: Transform mapping for users table',
    metadata: { attempt: 1, agent: 'claude' },
  },
  {
    timestamp: '2026-05-27T09:14:48.200Z',
    eventType: 'TASK_COMPLETE',
    level: 'task',
    scope: 'mapping-users',
    message: 'Task completed in 3100ms',
    metadata: { durationMs: 3100 },
  },
  {
    timestamp: '2026-05-27T09:14:45.100Z',
    eventType: 'TASK_START',
    level: 'task',
    scope: 'mapping-orders',
    message: 'Starting task: Transform mapping for orders table',
    metadata: { attempt: 1, agent: 'claude' },
  },
  {
    timestamp: '2026-05-27T09:14:45.200Z',
    eventType: 'TASK_START',
    level: 'task',
    scope: 'mapping-events',
    message: 'Starting task: Transform mapping for events table',
    metadata: { attempt: 1, agent: 'claude' },
  },
  {
    timestamp: '2026-05-27T09:14:51.000Z',
    eventType: 'CHECK_FAILED',
    level: 'task',
    scope: 'mapping-events',
    message: 'Check failed: Event payload Avro schema validation — metadata field type mismatch',
    metadata: { checkId: 'chk-event-schema', exitCode: 1 },
  },
  {
    timestamp: '2026-05-27T09:14:51.100Z',
    eventType: 'TASK_FAILED',
    level: 'task',
    scope: 'mapping-events',
    message: 'Task failed: Type mismatch on metadata column',
    metadata: { attempt: 1, error: 'Type mismatch: metadata column cannot be auto-coerced from jsonb to map<string>' },
  },
  {
    timestamp: '2026-05-27T09:14:51.200Z',
    eventType: 'GAP_DETECTED',
    level: 'task',
    scope: 'mapping-events',
    message: 'Gap detected: Missing output artifacts/mappings/events.json',
    metadata: { gapId: 'gap-001', type: 'output', severity: 'critical' },
  },
  {
    timestamp: '2026-05-27T09:14:51.300Z',
    eventType: 'CORRECTION_ATTEMPTED',
    level: 'task',
    scope: 'mapping-events',
    message: 'Attempting retry with custom coercer for jsonb -> map<string>',
    metadata: { attempt: 2, strategy: 'custom-coercer' },
  },
  {
    timestamp: '2026-05-27T09:14:57.500Z',
    eventType: 'TASK_FAILED',
    level: 'task',
    scope: 'mapping-events',
    message: 'Retry failed: unsupported nested array in metadata.tags',
    metadata: { attempt: 2, error: 'Custom coercer threw: unsupported nested array in metadata.tags' },
  },
  {
    timestamp: '2026-05-27T09:14:57.600Z',
    eventType: 'GAP_DETECTED',
    level: 'task',
    scope: 'mapping-events',
    message: 'Gap detected: Check failed on Avro schema validation',
    metadata: { gapId: 'gap-002', type: 'check-failed', severity: 'high' },
  },
  {
    timestamp: '2026-05-27T09:14:57.700Z',
    eventType: 'AWAITING_USER_INPUT',
    level: 'task',
    scope: 'mapping-events',
    message: 'Human review required: metadata column type coercion needs manual decision',
    metadata: { taskId: 'mapping-events', reason: 'Max retries exhausted for type coercion' },
  },
];

export const MOCK_SESSIONS: StudioSession[] = [
  {
    id: 'session-alpha',
    name: 'Data pipeline planning session',
    status: 'awaiting-feedback',
    goal: 'Design the ETL pipeline to migrate legacy PostgreSQL data into the event-driven warehouse with zero downtime',
    createdAt: '2026-05-26T16:30:00.000Z',
    feedbackHistory: [
      {
        id: 'fb-001',
        role: 'assistant',
        message: 'I have drafted a 12-task DAG for the data-pipeline playbook. The critical path runs through extract-schema -> generate-mappings -> build-etl-image -> deploy-production. Shall I proceed with compilation?',
        timestamp: '2026-05-26T16:32:00.000Z',
      },
      {
        id: 'fb-002',
        role: 'user',
        message: 'Add a separate validation step between extract and generate-mappings so we catch schema drift early.',
        timestamp: '2026-05-26T16:35:00.000Z',
      },
      {
        id: 'fb-003',
        role: 'assistant',
        message: 'Done. I inserted validate-schema as a dependency of generate-mappings. The new critical path is extract-schema -> validate-schema -> generate-mappings -> merge-mappings -> build-etl-image -> deploy-production. The task count is now 12.',
        timestamp: '2026-05-26T16:36:00.000Z',
      },
      {
        id: 'fb-004',
        role: 'user',
        message: 'Looks good. Also make sure the integration tests are a gateway — block production deploy until they pass.',
        timestamp: '2026-05-26T16:40:00.000Z',
      },
      {
        id: 'fb-005',
        role: 'assistant',
        message: 'Updated run-integration-tests to mode: gateway with deploy-production as its sole downstream. The DAG is ready for review.',
        timestamp: '2026-05-26T16:41:00.000Z',
      },
    ],
  },
  {
    id: 'session-beta',
    name: 'CI/CD pipeline design',
    status: 'published',
    goal: 'Set up a complete CI/CD pipeline using GitHub Actions for the monorepo with per-package caching',
    createdAt: '2026-05-25T10:00:00.000Z',
    feedbackHistory: [
      {
        id: 'fb-010',
        role: 'assistant',
        message: 'I propose an 8-task playbook: scaffold-workflows -> build-stage -> lint-stage -> test-stage -> deploy-stage, with build and lint running in parallel after scaffolding.',
        timestamp: '2026-05-25T10:05:00.000Z',
      },
      {
        id: 'fb-011',
        role: 'user',
        message: 'Ship it.',
        timestamp: '2026-05-25T10:06:00.000Z',
      },
      {
        id: 'fb-012',
        role: 'assistant',
        message: 'Playbook ci-cd-setup has been compiled and published. You can start a run from the playbooks view.',
        timestamp: '2026-05-25T10:07:00.000Z',
      },
    ],
  },
];

export const MOCK_SKILLS: SkillSummary[] = [
  {
    id: 'skill-code-review',
    name: 'Code Review',
    description: 'Performs structural and semantic code review with inline annotations, focusing on correctness, security, and maintainability',
  },
  {
    id: 'skill-test-generation',
    name: 'Test Generation',
    description: 'Generates unit and integration tests from source code, achieving high branch coverage with meaningful assertions',
  },
  {
    id: 'skill-doc-writing',
    name: 'Documentation Writing',
    description: 'Produces API reference docs, architecture decision records, and onboarding guides from codebase analysis',
  },
  {
    id: 'skill-security-scan',
    name: 'Security Scan',
    description: 'Runs SAST analysis, dependency vulnerability checks, and secret detection across the project',
  },
  {
    id: 'skill-refactoring',
    name: 'Refactoring',
    description: 'Applies safe, behavior-preserving refactoring patterns including extract-function, inline-variable, and module reorganization',
  },
];

export const MOCK_PROVIDERS: ProviderInfo[] = [
  {
    id: 'claude',
    name: 'Claude',
    available: true,
    model: 'claude-sonnet-4-20250514',
  },
  {
    id: 'codex',
    name: 'Codex',
    available: true,
    model: 'codex-mini-latest',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    available: false,
    model: 'gemini-2.5-pro',
  },
];
