// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 9 character entries from assets/quaternius/single_knight_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-knight-club", asset: "/assets/quaternius/single_knight_pack/club.glb", name: "Quat Knight: Club" },
  { slug: "quat-knight-helmet1", asset: "/assets/quaternius/single_knight_pack/helmet1.glb", name: "Quat Knight: Helmet1" },
  { slug: "quat-knight-helmet2", asset: "/assets/quaternius/single_knight_pack/helmet2.glb", name: "Quat Knight: Helmet2" },
  { slug: "quat-knight-helmet3", asset: "/assets/quaternius/single_knight_pack/helmet3.glb", name: "Quat Knight: Helmet3" },
  { slug: "quat-knight-katana", asset: "/assets/quaternius/single_knight_pack/katana.glb", name: "Quat Knight: Katana" },
  { slug: "quat-knight-knightcharacter", asset: "/assets/quaternius/single_knight_pack/knightcharacter.glb", name: "Quat Knight: Knightcharacter" },
  { slug: "quat-knight-shortsword", asset: "/assets/quaternius/single_knight_pack/shortsword.glb", name: "Quat Knight: Shortsword" },
  { slug: "quat-knight-shoulderpads", asset: "/assets/quaternius/single_knight_pack/shoulderpads.glb", name: "Quat Knight: Shoulderpads" },
  { slug: "quat-knight-sword", asset: "/assets/quaternius/single_knight_pack/sword.glb", name: "Quat Knight: Sword" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
