// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 12 character entries from assets/quaternius/animals_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-animal-alpaca", asset: "/assets/quaternius/animals_pack/alpaca.glb", name: "Quat Animal: Alpaca" },
  { slug: "quat-animal-bull", asset: "/assets/quaternius/animals_pack/bull.glb", name: "Quat Animal: Bull" },
  { slug: "quat-animal-cow", asset: "/assets/quaternius/animals_pack/cow.glb", name: "Quat Animal: Cow" },
  { slug: "quat-animal-deer", asset: "/assets/quaternius/animals_pack/deer.glb", name: "Quat Animal: Deer" },
  { slug: "quat-animal-donkey", asset: "/assets/quaternius/animals_pack/donkey.glb", name: "Quat Animal: Donkey" },
  { slug: "quat-animal-fox", asset: "/assets/quaternius/animals_pack/fox.glb", name: "Quat Animal: Fox" },
  { slug: "quat-animal-horse", asset: "/assets/quaternius/animals_pack/horse.glb", name: "Quat Animal: Horse" },
  { slug: "quat-animal-horse_white", asset: "/assets/quaternius/animals_pack/horse_white.glb", name: "Quat Animal: Horse White" },
  { slug: "quat-animal-husky", asset: "/assets/quaternius/animals_pack/husky.glb", name: "Quat Animal: Husky" },
  { slug: "quat-animal-shibainu", asset: "/assets/quaternius/animals_pack/shibainu.glb", name: "Quat Animal: Shibainu" },
  { slug: "quat-animal-stag", asset: "/assets/quaternius/animals_pack/stag.glb", name: "Quat Animal: Stag" },
  { slug: "quat-animal-wolf", asset: "/assets/quaternius/animals_pack/wolf.glb", name: "Quat Animal: Wolf" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
