// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 6 character entries from assets/quaternius/easy_enemies_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-enemy-frog", asset: "/assets/quaternius/easy_enemies_pack/frog.glb", name: "Quat Enemy: Frog" },
  { slug: "quat-enemy-rat", asset: "/assets/quaternius/easy_enemies_pack/rat.glb", name: "Quat Enemy: Rat" },
  { slug: "quat-enemy-snake", asset: "/assets/quaternius/easy_enemies_pack/snake.glb", name: "Quat Enemy: Snake" },
  { slug: "quat-enemy-snake_angry", asset: "/assets/quaternius/easy_enemies_pack/snake_angry.glb", name: "Quat Enemy: Snake Angry" },
  { slug: "quat-enemy-spider", asset: "/assets/quaternius/easy_enemies_pack/spider.glb", name: "Quat Enemy: Spider" },
  { slug: "quat-enemy-wasp", asset: "/assets/quaternius/easy_enemies_pack/wasp.glb", name: "Quat Enemy: Wasp" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
