// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 20 prop entries from assets/kenney/mini-arcade.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "mini-arcade-air-hockey", asset: "/assets/kenney/mini-arcade/air-hockey.glb", name: "Mini Arcade: Hockey" },
  { slug: "mini-arcade-arcade-machine", asset: "/assets/kenney/mini-arcade/arcade-machine.glb", name: "Mini Arcade: Machine" },
  { slug: "mini-arcade-basketball-game", asset: "/assets/kenney/mini-arcade/basketball-game.glb", name: "Mini Arcade: Game" },
  { slug: "mini-arcade-cash-register", asset: "/assets/kenney/mini-arcade/cash-register.glb", name: "Mini Arcade: Register" },
  { slug: "mini-arcade-character-employee", asset: "/assets/kenney/mini-arcade/character-employee.glb", name: "Mini Arcade: Employee" },
  { slug: "mini-arcade-character-gamer", asset: "/assets/kenney/mini-arcade/character-gamer.glb", name: "Mini Arcade: Gamer" },
  { slug: "mini-arcade-claw-machine", asset: "/assets/kenney/mini-arcade/claw-machine.glb", name: "Mini Arcade: Machine" },
  { slug: "mini-arcade-column", asset: "/assets/kenney/mini-arcade/column.glb", name: "Mini Arcade: Column" },
  { slug: "mini-arcade-dance-machine", asset: "/assets/kenney/mini-arcade/dance-machine.glb", name: "Mini Arcade: Machine" },
  { slug: "mini-arcade-floor", asset: "/assets/kenney/mini-arcade/floor.glb", name: "Mini Arcade: Floor" },
  { slug: "mini-arcade-gambling-machine", asset: "/assets/kenney/mini-arcade/gambling-machine.glb", name: "Mini Arcade: Machine" },
  { slug: "mini-arcade-pinball", asset: "/assets/kenney/mini-arcade/pinball.glb", name: "Mini Arcade: Pinball" },
  { slug: "mini-arcade-prize-wheel", asset: "/assets/kenney/mini-arcade/prize-wheel.glb", name: "Mini Arcade: Wheel" },
  { slug: "mini-arcade-prizes", asset: "/assets/kenney/mini-arcade/prizes.glb", name: "Mini Arcade: Prizes" },
  { slug: "mini-arcade-ticket-machine", asset: "/assets/kenney/mini-arcade/ticket-machine.glb", name: "Mini Arcade: Machine" },
  { slug: "mini-arcade-vending-machine", asset: "/assets/kenney/mini-arcade/vending-machine.glb", name: "Mini Arcade: Machine" },
  { slug: "mini-arcade-wall-corner", asset: "/assets/kenney/mini-arcade/wall-corner.glb", name: "Mini Arcade: Corner" },
  { slug: "mini-arcade-wall-door-rotate", asset: "/assets/kenney/mini-arcade/wall-door-rotate.glb", name: "Mini Arcade: Door-Rotate" },
  { slug: "mini-arcade-wall-window", asset: "/assets/kenney/mini-arcade/wall-window.glb", name: "Mini Arcade: Window" },
  { slug: "mini-arcade-wall", asset: "/assets/kenney/mini-arcade/wall.glb", name: "Mini Arcade: Wall" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
