// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 53 prop entries from assets/furniture.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "furn-armchair", asset: "/assets/furniture/armchair.gltf", name: "Furniture: Armchair" },
  { slug: "furn-armchair_pillows", asset: "/assets/furniture/armchair_pillows.gltf", name: "Furniture: Armchair Pillows" },
  { slug: "furn-bed_double_a", asset: "/assets/furniture/bed_double_a.gltf", name: "Furniture: Bed Double A" },
  { slug: "furn-bed_double_b", asset: "/assets/furniture/bed_double_b.gltf", name: "Furniture: Bed Double B" },
  { slug: "furn-bed_single_a", asset: "/assets/furniture/bed_single_a.gltf", name: "Furniture: Bed Single A" },
  { slug: "furn-bed_single_b", asset: "/assets/furniture/bed_single_b.gltf", name: "Furniture: Bed Single B" },
  { slug: "furn-book_set", asset: "/assets/furniture/book_set.gltf", name: "Furniture: Book Set" },
  { slug: "furn-book_single", asset: "/assets/furniture/book_single.gltf", name: "Furniture: Book Single" },
  { slug: "furn-cabinet_medium", asset: "/assets/furniture/cabinet_medium.gltf", name: "Furniture: Cabinet Medium" },
  { slug: "furn-cabinet_medium_decorated", asset: "/assets/furniture/cabinet_medium_decorated.gltf", name: "Furniture: Cabinet Medium Decorated" },
  { slug: "furn-cabinet_small", asset: "/assets/furniture/cabinet_small.gltf", name: "Furniture: Cabinet Small" },
  { slug: "furn-cabinet_small_decorated", asset: "/assets/furniture/cabinet_small_decorated.gltf", name: "Furniture: Cabinet Small Decorated" },
  { slug: "furn-cactus_medium_a", asset: "/assets/furniture/cactus_medium_a.gltf", name: "Furniture: Cactus Medium A" },
  { slug: "furn-cactus_medium_b", asset: "/assets/furniture/cactus_medium_b.gltf", name: "Furniture: Cactus Medium B" },
  { slug: "furn-cactus_small_a", asset: "/assets/furniture/cactus_small_a.gltf", name: "Furniture: Cactus Small A" },
  { slug: "furn-cactus_small_b", asset: "/assets/furniture/cactus_small_b.gltf", name: "Furniture: Cactus Small B" },
  { slug: "furn-chair_a", asset: "/assets/furniture/chair_a.gltf", name: "Furniture: Chair A" },
  { slug: "furn-chair_a_wood", asset: "/assets/furniture/chair_a_wood.gltf", name: "Furniture: Chair A Wood" },
  { slug: "furn-chair_b", asset: "/assets/furniture/chair_b.gltf", name: "Furniture: Chair B" },
  { slug: "furn-chair_b_wood", asset: "/assets/furniture/chair_b_wood.gltf", name: "Furniture: Chair B Wood" },
  { slug: "furn-chair_c", asset: "/assets/furniture/chair_c.gltf", name: "Furniture: Chair C" },
  { slug: "furn-chair_stool", asset: "/assets/furniture/chair_stool.gltf", name: "Furniture: Chair Stool" },
  { slug: "furn-chair_stool_wood", asset: "/assets/furniture/chair_stool_wood.gltf", name: "Furniture: Chair Stool Wood" },
  { slug: "furn-couch", asset: "/assets/furniture/couch.gltf", name: "Furniture: Couch" },
  { slug: "furn-couch_pillows", asset: "/assets/furniture/couch_pillows.gltf", name: "Furniture: Couch Pillows" },
  { slug: "furn-lamp_standing", asset: "/assets/furniture/lamp_standing.gltf", name: "Furniture: Lamp Standing" },
  { slug: "furn-lamp_table", asset: "/assets/furniture/lamp_table.gltf", name: "Furniture: Lamp Table" },
  { slug: "furn-pictureframe_large_a", asset: "/assets/furniture/pictureframe_large_a.gltf", name: "Furniture: Pictureframe Large A" },
  { slug: "furn-pictureframe_large_b", asset: "/assets/furniture/pictureframe_large_b.gltf", name: "Furniture: Pictureframe Large B" },
  { slug: "furn-pictureframe_medium", asset: "/assets/furniture/pictureframe_medium.gltf", name: "Furniture: Pictureframe Medium" },
  { slug: "furn-pictureframe_small_a", asset: "/assets/furniture/pictureframe_small_a.gltf", name: "Furniture: Pictureframe Small A" },
  { slug: "furn-pictureframe_small_b", asset: "/assets/furniture/pictureframe_small_b.gltf", name: "Furniture: Pictureframe Small B" },
  { slug: "furn-pictureframe_small_c", asset: "/assets/furniture/pictureframe_small_c.gltf", name: "Furniture: Pictureframe Small C" },
  { slug: "furn-pictureframe_standing_a", asset: "/assets/furniture/pictureframe_standing_a.gltf", name: "Furniture: Pictureframe Standing A" },
  { slug: "furn-pictureframe_standing_b", asset: "/assets/furniture/pictureframe_standing_b.gltf", name: "Furniture: Pictureframe Standing B" },
  { slug: "furn-pillow_a", asset: "/assets/furniture/pillow_a.gltf", name: "Furniture: Pillow A" },
  { slug: "furn-pillow_b", asset: "/assets/furniture/pillow_b.gltf", name: "Furniture: Pillow B" },
  { slug: "furn-rug_oval_a", asset: "/assets/furniture/rug_oval_a.gltf", name: "Furniture: Rug Oval A" },
  { slug: "furn-rug_oval_b", asset: "/assets/furniture/rug_oval_b.gltf", name: "Furniture: Rug Oval B" },
  { slug: "furn-rug_rectangle_a", asset: "/assets/furniture/rug_rectangle_a.gltf", name: "Furniture: Rug Rectangle A" },
  { slug: "furn-rug_rectangle_b", asset: "/assets/furniture/rug_rectangle_b.gltf", name: "Furniture: Rug Rectangle B" },
  { slug: "furn-rug_rectangle_stripes_a", asset: "/assets/furniture/rug_rectangle_stripes_a.gltf", name: "Furniture: Rug Rectangle Stripes A" },
  { slug: "furn-rug_rectangle_stripes_b", asset: "/assets/furniture/rug_rectangle_stripes_b.gltf", name: "Furniture: Rug Rectangle Stripes B" },
  { slug: "furn-shelf_a_big", asset: "/assets/furniture/shelf_a_big.gltf", name: "Furniture: Shelf A Big" },
  { slug: "furn-shelf_a_small", asset: "/assets/furniture/shelf_a_small.gltf", name: "Furniture: Shelf A Small" },
  { slug: "furn-shelf_b_large", asset: "/assets/furniture/shelf_b_large.gltf", name: "Furniture: Shelf B Large" },
  { slug: "furn-shelf_b_large_decorated", asset: "/assets/furniture/shelf_b_large_decorated.gltf", name: "Furniture: Shelf B Large Decorated" },
  { slug: "furn-shelf_b_small", asset: "/assets/furniture/shelf_b_small.gltf", name: "Furniture: Shelf B Small" },
  { slug: "furn-shelf_b_small_decorated", asset: "/assets/furniture/shelf_b_small_decorated.gltf", name: "Furniture: Shelf B Small Decorated" },
  { slug: "furn-table_low", asset: "/assets/furniture/table_low.gltf", name: "Furniture: Table Low" },
  { slug: "furn-table_medium", asset: "/assets/furniture/table_medium.gltf", name: "Furniture: Table Medium" },
  { slug: "furn-table_medium_long", asset: "/assets/furniture/table_medium_long.gltf", name: "Furniture: Table Medium Long" },
  { slug: "furn-table_small", asset: "/assets/furniture/table_small.gltf", name: "Furniture: Table Small" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
