// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 7 character entries from assets/quaternius/fish_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-fish-dolphin", asset: "/assets/quaternius/fish_pack/dolphin.glb", name: "Quat Fish: Dolphin" },
  { slug: "quat-fish-fish1", asset: "/assets/quaternius/fish_pack/fish1.glb", name: "Quat Fish: Fish1" },
  { slug: "quat-fish-fish2", asset: "/assets/quaternius/fish_pack/fish2.glb", name: "Quat Fish: Fish2" },
  { slug: "quat-fish-fish3", asset: "/assets/quaternius/fish_pack/fish3.glb", name: "Quat Fish: Fish3" },
  { slug: "quat-fish-manta_ray", asset: "/assets/quaternius/fish_pack/manta_ray.glb", name: "Quat Fish: Manta Ray" },
  { slug: "quat-fish-shark", asset: "/assets/quaternius/fish_pack/shark.glb", name: "Quat Fish: Shark" },
  { slug: "quat-fish-whale", asset: "/assets/quaternius/fish_pack/whale.glb", name: "Quat Fish: Whale" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "character", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
