// AUTO-GENERATED by scripts/gen-kaykit-manifests.ts — do not edit by hand.
// 53 prop entries from assets/quaternius/platformer_pack.

import { GltfModel, widgetToAssetModule } from '@lego';
import type { AssetModule } from '../../src/types.js';

interface PackEntry { slug: string; asset: string; name: string; }

const ENTRIES: PackEntry[] = [
  { slug: "quat-platformer-beartrap_closed", asset: "/assets/quaternius/platformer_pack/beartrap_closed.glb", name: "Quat Platformer: Beartrap Closed" },
  { slug: "quat-platformer-beartrap_open", asset: "/assets/quaternius/platformer_pack/beartrap_open.glb", name: "Quat Platformer: Beartrap Open" },
  { slug: "quat-platformer-bomb", asset: "/assets/quaternius/platformer_pack/bomb.glb", name: "Quat Platformer: Bomb" },
  { slug: "quat-platformer-cloud1", asset: "/assets/quaternius/platformer_pack/cloud1.glb", name: "Quat Platformer: Cloud1" },
  { slug: "quat-platformer-cloud2", asset: "/assets/quaternius/platformer_pack/cloud2.glb", name: "Quat Platformer: Cloud2" },
  { slug: "quat-platformer-cloud3", asset: "/assets/quaternius/platformer_pack/cloud3.glb", name: "Quat Platformer: Cloud3" },
  { slug: "quat-platformer-cloud4", asset: "/assets/quaternius/platformer_pack/cloud4.glb", name: "Quat Platformer: Cloud4" },
  { slug: "quat-platformer-cloud5", asset: "/assets/quaternius/platformer_pack/cloud5.glb", name: "Quat Platformer: Cloud5" },
  { slug: "quat-platformer-coin", asset: "/assets/quaternius/platformer_pack/coin.glb", name: "Quat Platformer: Coin" },
  { slug: "quat-platformer-crate", asset: "/assets/quaternius/platformer_pack/crate.glb", name: "Quat Platformer: Crate" },
  { slug: "quat-platformer-fence", asset: "/assets/quaternius/platformer_pack/fence.glb", name: "Quat Platformer: Fence" },
  { slug: "quat-platformer-flag", asset: "/assets/quaternius/platformer_pack/flag.glb", name: "Quat Platformer: Flag" },
  { slug: "quat-platformer-grass", asset: "/assets/quaternius/platformer_pack/grass.glb", name: "Quat Platformer: Grass" },
  { slug: "quat-platformer-grass1", asset: "/assets/quaternius/platformer_pack/grass1.glb", name: "Quat Platformer: Grass1" },
  { slug: "quat-platformer-grass2", asset: "/assets/quaternius/platformer_pack/grass2.glb", name: "Quat Platformer: Grass2" },
  { slug: "quat-platformer-heart_full", asset: "/assets/quaternius/platformer_pack/heart_full.glb", name: "Quat Platformer: Heart Full" },
  { slug: "quat-platformer-heart_half", asset: "/assets/quaternius/platformer_pack/heart_half.glb", name: "Quat Platformer: Heart Half" },
  { slug: "quat-platformer-key", asset: "/assets/quaternius/platformer_pack/key.glb", name: "Quat Platformer: Key" },
  { slug: "quat-platformer-ladder_long", asset: "/assets/quaternius/platformer_pack/ladder_long.glb", name: "Quat Platformer: Ladder Long" },
  { slug: "quat-platformer-ladder_medium", asset: "/assets/quaternius/platformer_pack/ladder_medium.glb", name: "Quat Platformer: Ladder Medium" },
  { slug: "quat-platformer-ladder_short", asset: "/assets/quaternius/platformer_pack/ladder_short.glb", name: "Quat Platformer: Ladder Short" },
  { slug: "quat-platformer-lever", asset: "/assets/quaternius/platformer_pack/lever.glb", name: "Quat Platformer: Lever" },
  { slug: "quat-platformer-movingplatform", asset: "/assets/quaternius/platformer_pack/movingplatform.glb", name: "Quat Platformer: Movingplatform" },
  { slug: "quat-platformer-movingplatform_long", asset: "/assets/quaternius/platformer_pack/movingplatform_long.glb", name: "Quat Platformer: Movingplatform Long" },
  { slug: "quat-platformer-mushroom", asset: "/assets/quaternius/platformer_pack/mushroom.glb", name: "Quat Platformer: Mushroom" },
  { slug: "quat-platformer-pipe", asset: "/assets/quaternius/platformer_pack/pipe.glb", name: "Quat Platformer: Pipe" },
  { slug: "quat-platformer-platform_bottomleft", asset: "/assets/quaternius/platformer_pack/platform_bottomleft.glb", name: "Quat Platformer: Platform Bottomleft" },
  { slug: "quat-platformer-platform_bottommiddle", asset: "/assets/quaternius/platformer_pack/platform_bottommiddle.glb", name: "Quat Platformer: Platform Bottommiddle" },
  { slug: "quat-platformer-platform_bottomright", asset: "/assets/quaternius/platformer_pack/platform_bottomright.glb", name: "Quat Platformer: Platform Bottomright" },
  { slug: "quat-platformer-platform_centerleft", asset: "/assets/quaternius/platformer_pack/platform_centerleft.glb", name: "Quat Platformer: Platform Centerleft" },
  { slug: "quat-platformer-platform_centermiddle", asset: "/assets/quaternius/platformer_pack/platform_centermiddle.glb", name: "Quat Platformer: Platform Centermiddle" },
  { slug: "quat-platformer-platform_centerright", asset: "/assets/quaternius/platformer_pack/platform_centerright.glb", name: "Quat Platformer: Platform Centerright" },
  { slug: "quat-platformer-platform_topleft", asset: "/assets/quaternius/platformer_pack/platform_topleft.glb", name: "Quat Platformer: Platform Topleft" },
  { slug: "quat-platformer-platform_topmiddle", asset: "/assets/quaternius/platformer_pack/platform_topmiddle.glb", name: "Quat Platformer: Platform Topmiddle" },
  { slug: "quat-platformer-platform_topright", asset: "/assets/quaternius/platformer_pack/platform_topright.glb", name: "Quat Platformer: Platform Topright" },
  { slug: "quat-platformer-rock1", asset: "/assets/quaternius/platformer_pack/rock1.glb", name: "Quat Platformer: Rock1" },
  { slug: "quat-platformer-rock2", asset: "/assets/quaternius/platformer_pack/rock2.glb", name: "Quat Platformer: Rock2" },
  { slug: "quat-platformer-rock3", asset: "/assets/quaternius/platformer_pack/rock3.glb", name: "Quat Platformer: Rock3" },
  { slug: "quat-platformer-rock4", asset: "/assets/quaternius/platformer_pack/rock4.glb", name: "Quat Platformer: Rock4" },
  { slug: "quat-platformer-rope_long", asset: "/assets/quaternius/platformer_pack/rope_long.glb", name: "Quat Platformer: Rope Long" },
  { slug: "quat-platformer-rope_short", asset: "/assets/quaternius/platformer_pack/rope_short.glb", name: "Quat Platformer: Rope Short" },
  { slug: "quat-platformer-sign_left", asset: "/assets/quaternius/platformer_pack/sign_left.glb", name: "Quat Platformer: Sign Left" },
  { slug: "quat-platformer-sign_leftright", asset: "/assets/quaternius/platformer_pack/sign_leftright.glb", name: "Quat Platformer: Sign Leftright" },
  { slug: "quat-platformer-sign_right", asset: "/assets/quaternius/platformer_pack/sign_right.glb", name: "Quat Platformer: Sign Right" },
  { slug: "quat-platformer-spike_group", asset: "/assets/quaternius/platformer_pack/spike_group.glb", name: "Quat Platformer: Spike Group" },
  { slug: "quat-platformer-spike_single", asset: "/assets/quaternius/platformer_pack/spike_single.glb", name: "Quat Platformer: Spike Single" },
  { slug: "quat-platformer-spikes_platform", asset: "/assets/quaternius/platformer_pack/spikes_platform.glb", name: "Quat Platformer: Spikes Platform" },
  { slug: "quat-platformer-star", asset: "/assets/quaternius/platformer_pack/star.glb", name: "Quat Platformer: Star" },
  { slug: "quat-platformer-tree1", asset: "/assets/quaternius/platformer_pack/tree1.glb", name: "Quat Platformer: Tree1" },
  { slug: "quat-platformer-tree2", asset: "/assets/quaternius/platformer_pack/tree2.glb", name: "Quat Platformer: Tree2" },
  { slug: "quat-platformer-tree3", asset: "/assets/quaternius/platformer_pack/tree3.glb", name: "Quat Platformer: Tree3" },
  { slug: "quat-platformer-tree4", asset: "/assets/quaternius/platformer_pack/tree4.glb", name: "Quat Platformer: Tree4" },
  { slug: "quat-platformer-yellowbox", asset: "/assets/quaternius/platformer_pack/yellowbox.glb", name: "Quat Platformer: Yellowbox" },
];

const modules: AssetModule[] = ENTRIES.map((e) => widgetToAssetModule(
  e.slug,
  { kind: "prop", name: e.name },
  new GltfModel({ asset: e.asset }),
));

export default modules;
